### ISSUE TITLE
Update Embed + Text widget intro text

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1023]
Update text to:
>This widget embeds an oEmbed-supported web resource and a text block to the left or right of it. Examples of oEmbed-supported resources include those from YouTube, Twitter, Flickr, and SlideShare.

Previous commentary below
---

embed+text widget states:

"This widget embeds a web resource and a text block to the left or right of it."

For purposes of this widget, how is "web resource" defined? I am not able to enter any URL and have it render on the page using this widget.

Wikipedia says:

"A web resource is anything that can be obtained from the World Wide Web. Some examples are web pages, e-mail, information from databases, and web services."

It would be helpful to have an example of a web resource that renders using this widget -- or  instead -- having validation that this widget doesn't work, if that is what is happening.

**Comment by ggeisler** [comment]
@caaster  See https://exhibits.stanford.edu/new-exhibit/home.exhibit-home for several examples (YouTube, Flickr, Twitter, SlideShare) of using the Embed + Text widget to embed a web resource.

I think the issue (though I am sure I am **not** the best person to explain this) is that the "web resource" needs to be supported through oEmbed by the source provider. I think this has come up before as something we need to document to make more clear to curators what sort of resources will work in the widget.

It's not particularly user-friendly, but perhaps we could update the widget text to something like "This widget embeds an oEmbed-supported web resource and a text block to the left or right of it. Examples of oEmbed-supported resources include those from YouTube, Twitter, Flickr, and Slideshare."

The problem is we can't provide an exhaustive list of providers in the widget text, and I'm not sure there is a user-friendly page listing providers we can simply link to. The Providers section at https://oembed.com/ lists a bunch, but that page is oriented for developers.

At least part of the solution is more thorough documentation for the widgets (not in the widget panel itself but in the documentation produced by the Service Team), as we've discussed on the Service Team.

If it is technically feasible to know whether the URL provided is invalid, displaying an error message when rendering the saved page might be an additional part of the solution. But we'd need a developer to chime in on how feasible that might be.

**Comment by caaster** [comment]
@ggeisler -- aha! so this is the oembed thing. I am recalling a discussion now with either you or @jkeck. Gary -- if you have no objections, I'd vote for updating the widget text as you suggest. Then, when we (service team) creates the widget-specific documentation (which should happen in the first half of 2018 I'm hoping) we can go into more detail. As it stands now, this widget is an exercise in frustration for 95% of users, and I would like to minimize frustration where possible.

**Comment by ggeisler** [comment]
@caaster Sure, sounds fine to me.

@jkeck Does this text sound technically accurate to you?

> This widget embeds an oEmbed-supported web resource and a text block to the left or right of it. Examples of oEmbed-supported resources include those from YouTube, Twitter, Flickr, and SlideShare.

If so, maybe we can just update the title of this ticket to something like "Update Embed + Text widget intro text" and someone can just replace the existing intro sentence with the new text above.

**Comment by camillevilla** [comment]
FYI: this change needed to be made upstream in Spotlight. I have a PR open at projectblacklight/spotlight#1910
