### ISSUE TITLE
Search box widget (design)

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1025]
As a curator/exhibit admin, I want to add a prominent search box widget to a page (e.g. the home page, or to a browse category display), so that the user knows they can search immediately. If the user enters a search from the browse category search widget, they should have the search scoped appropriately.

**Comment by ggeisler** [comment]
I think there are three places where this search box might be added:

* Homepage - I'm not sure it makes sense to add a search box to the homepage. It would only duplicate the function of the menu bar search box and I'm not sure presenting it more directly (e.g., at the top of the facet sidebar) -- although I see the argument that it would make it a bit more clear or findable to the user -- justifies having duplicate search boxes. Unlike a results page, if a user selects a facet value from the homepage they are then removed from the homepage context (they end up at a results page) so from the homepage you either enter a search term or select a facet value; you can't combine them there, so having a search box in close proximity to the facets seems less critical to me.

* Results page - I basically have the same concerns for adding a search box to the results page, though it could make a little more sense here. It wouldn't function any differently than the existing menu bar search box (adding a term just further restricts the result set) so the only justification for it is that it is likely more noticeable to a user who is refining a result set in multiple steps if it is located closer to the facet controls. But I still wonder if this convenience is worth having two search boxes on the page that do exactly the same thing.

* Browse category page - This one makes more sense, especially for the VT use case where, as additional tribunal items are added, they might use browse categories to delineate different tribunal items, and each of those categories could contain a large number of items. A user only interested in a given tribunal would benefit from using the browse category to easily jump into that tribunal and then be able to search within it, without having to know how to use the facets to restrict results to that tribunal. 

Mockups for the browse category page are below. I wonder if we should implement this (after discussing and refining the design, if necessary) first, and after showing it to the VT stakeholders have another discussion to see if they really think we need the search box on the home or results pages (especially since I'm not sure we've heard this request from any previous exhibit stakeholder)?

**Comment by ggeisler** [comment]
Mockups for adding a search box to the browse category page are below. The mockups assume:

* Adding a search box to a browse category page is optional, and done on a per-browse category page basis (so a given exhibit can show it on some browse pages and not others).
* The default setting is to **not** show the search box (so there are no ramifications for existing exhibit browse pages).

(Also, one potential hurdle for implementation might be with clearly distinguishing the two search boxes on the same page for accessibility purposes. For reference, we do show two search boxes on the collection page in Arclight (e.g., https://arclight-demo.projectblacklight.org/catalog/umich-bhl-0234), though I can't remember if we have addressed the accessibility issue there yet.)

## Configuration
Add one setting to the Curation > Browse > Edit Browse Category description page, which enables the curator to display the search box on the browse category page:

<img width="517" alt="browse-page-searchbox-admin-config" src="https://user-images.githubusercontent.com/101482/34226934-98959ddc-e588-11e7-94e6-473428a25ecc.png">

## Initial display of a browse category page with the search box enabled
If the configuration option is enabled for a browse category, the page displays a new section at the top of the results (note 1 in the mockup):

<img width="641" alt="browse-page-searchbox" src="https://user-images.githubusercontent.com/101482/34227050-0249c56e-e589-11e7-9c4b-e06eb8751792.png">

## Browse category page with a successful search
If the user enters a search term that matches some or all of the items in the browse category, the results area is updated as shown below. There are three pieces added:

1. A "clear search term" icon in the search box
2. A message notifying the user of how many items matched their term
3. A message that enables the user to easily broaden their search to the all exhibit items by clicking a link

<img width="622" alt="browse-page-searchbox-results" src="https://user-images.githubusercontent.com/101482/34227301-e8979da2-e589-11e7-886d-f5d3aaa75f29.png">

## Browse category page with an unsuccessful search
If the terms the user searches for don't match any items in the browse category, no result items are shown, and the messages in notes 2 and 3 above are changed a bit:

<img width="624" alt="browse-page-searchbox-no-results" src="https://user-images.githubusercontent.com/101482/34227394-302cbbf2-e58a-11e7-9f60-86a4d1f8182d.png">

**Comment by anarchivist** [comment]
I think starting with this as a feature added to browse categories makes sense as a starting point. This seems like a good way to limit the scope for a first pass and get feedback as @ggeisler suggests.

@ggeisler 💬 

> The mockups assume:
>
> * Adding a search box to a browse category page is optional, and done on a per-browse category page basis (so a given exhibit can show it on some browse pages and not others).
> * The default setting is to not show the search box (so there are no ramifications for existing exhibit browse pages).

These are both reasonable assumptions. I think the mockups look good - should I present them to the stakeholders before we implement them?

> Also, one potential hurdle for implementation might be with clearly distinguishing the two search boxes on the same page for accessibility purposes. For reference, we do show two search boxes on the collection page in Arclight (e.g., https://arclight-demo.projectblacklight.org/catalog/umich-bhl-0234), though I can't remember if we have addressed the accessibility issue there yet.

I think we added `<label/>` elements to distinguish between the two search boxes. 

> Because this ticket is in the Exhibits repo, I've mocked it up as a SUL exhibit, but maybe we should discuss whether, if we decide to implement it, it should be done in the Spotlight repo?

Maybe at standup today or Friday?

**Comment by anarchivist** [comment]
As of winter break, I shared the mocks with the stakeholders, but am awaiting feedback or a followup conversation. I'll touch base with them once we're back.

**Comment by anarchivist** [comment]
We're ready to go on implementation, based on a preliminary review with the stakeholders. There may still be some interest to add a prominent search bar as described in the first few comments but the stakeholders are willing to wait to investigate that one they see an implementation.
