### ISSUE TITLE
When navigating forward and back on the Mirador viewer, extra index/search/layers menu is added to the left-hand panel

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1067]
See screenshot
<img width="1241" alt="screen shot 2018-01-26 at 3 49 32 pm" src="https://user-images.githubusercontent.com/3210225/35465566-d9a45bce-02b1-11e8-8066-4d9d022dd287.png">

Example is: https://exhibits.stanford.edu/time-travel-japan/catalog/gz963yg6275

**Comment by aeschylus** [comment]
This seems to be related to the availability of the search service in the manifest as generated by PURL: 
https://github.com/sul-dlss/purl/blob/master/app/models/iiif3_presentation_manifest.rb#L24
https://github.com/sul-dlss/purl/blob/master/app/models/iiif_presentation_manifest.rb#L98

Basically, if there is no content search available, the manifest has `service: [ null ]` in the manifest's service description. I don't think this is valid IIIF, but if it is, we should file a ticket to add error handling to Mirador for these cases. Otherwise, we should add a case to not append a service key to the manifests in PURL.

I'll ask the IIIF-discuss list about the validity of a null array and an empty array. @anarchivist and I had a look at some iiif-discuss archived posts and the specs and didn't find any definitive statement about these cases.

**Comment by aeschylus** [comment]
Looks like the UV also breaks on these manifests (when configured to open in search mode).

**Comment by anarchivist** [comment]
Fixed by sul-dlss/purl#208; @caaster, please confirm.

![screenshot](http://g.recordit.co/UWKYCOAOP0.gif)

**Comment by caaster** [comment]
Fix confirmed.
