### ISSUE TITLE
Change size/display of sul-embed frame for item embed widget

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1196]
The exhibit creator for the Baltic exhibit recently filed feedback about this. Her workaround was to feature her videos from youtube, instead of those same videos from the SDR. We really don't want this to happen! Here are screenshots of the youtube widget & item embed widget for her exhibit.

<img width="1130" alt="screen shot 2018-06-07 at 10 01 49 am" src="https://user-images.githubusercontent.com/3210225/41114949-c3d558c0-6a3a-11e8-9cd1-43224960c5ff.png">

<img width="1197" alt="screen shot 2018-06-07 at 10 03 22 am" src="https://user-images.githubusercontent.com/3210225/41114956-c7adecbe-6a3a-11e8-945d-6420729e9b24.png">

**Comment by camillevilla** [comment]
I spent a little bit of time poking around with this but don't have recommendations for how this could be implemented yet. 

If anyone else is curious, I set up a test page in stage for comparison
https://exhibits-stage.stanford.edu/bug-testing/home.exhibit-home

Code in #930 may also be of interest.

**Comment by ggeisler** [comment]
@camillevilla I'm trying to understand this ticket and what design might be needed and went to your test page exhibit but get a `You need to sign in or sign up before continuing.` message.

Can you add me as a curator to that exhibit (unless you know of another reason for that error message)?

**Comment by ggeisler** [comment]
Looking at this a bit more, I'm not sure it's really a design issue. Or maybe it's just a simple design issue.

It appears that when we display the embed viewer in a feature page, we display it with a height of 600px. When we display the embed view on a Purl page, we display it with a height of 400px.

Feature page in exhibits:

<img width="913" alt="no_boundaries_-_the_digital_nomads_of_estonia_collection___the_baltic_video_archive_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/101482/49618406-b6503600-f975-11e8-9a00-99476cd651da.png">

Same object's Purl page:

<img width="1192" alt="oral_history_interview_with_steve_jurvetson__may_27__2016___stanford_digital_repository" src="https://user-images.githubusercontent.com/101482/49618708-c4528680-f976-11e8-8041-c02762135033.png">

In an exhibit feature page, the embed viewer might have reduced width (if the curator adds text to the widget, as in the example above), but I don't think that needs to influence how tall the viewer is. (In the example above, the play button might float on top of the thumbnail image, but that seems fine to me.) In other words, I think we can display it with a consistent height no matter the context.

So the design solution is just to reduce the viewer height to 400px from 600px.

I'm not sure if I'm overlooking something here, but for now I'm going to remove the Design Needed label and assume the issue is just a technical one of figuring out how to get the viewer to display at 400px high. If I am missing something and the issue needs more design thought, just add the Design Needed label back, along with more explanation of what design consideration might be needed.

**Comment by camillevilla** [comment]
hi @ggeisler! I've added you to the the exhibit. In one example I edited the height and width of the YouTube embed HTML manually.
```html
<!-- edited height and width -->
<iframe src='https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/sf228vs1962&hide_title=true' height='200px' width='50%' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' allowfullscreen />
```

**Comment by ggeisler** [comment]
Thanks @camillevilla, I can see the page now.

I guess I'm a little confused, though. I thought this ticket was just about the Item Embed widget? 

The iFrame widget looks fine to me as is (the top version on your bug testing page). That widget doesn't have the option of a text block, so doesn't have the same issues involved as the Item Embed widget, and the height as is is 400px, which is what I'm recommending for the Item Embed widget. 

I might be missing something but am wondering if there is any reason focusing just on adjusting the height of the Item Embed widget wouldn't solve the original problem outline in this ticket?
