### ISSUE TITLE
"SAVE" button intermittently failing

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1206]
We received two reports yesterday of the "Save" button failing, by exhibit creators working on the SFTJF exhibit (https://exhibits.stanford.edu/sftjf).

Report #1: ticket filed at 12:47 pm, 24 June 2018, from: https://exhibits.stanford.edu/sftjf/feature/first-generation-jazzmen

Report #2: ticket filed at 1:10 pm, 24 June 2018, from: https://exhibits.stanford.edu/sftjf/feature/don-ewell

**Comment by caaster** [comment]
This issue is still happening. Gary and Cathy have experienced it many times, along with many different exhibit creators. It is understandably challenging to chase down because it seems it is not being logged, and it is not instantly repeatable as the behavior is random.

Here is a suggestion: try to edit a page over and over until you hit the problem, as the first step in working on the issue. If create a page with a lot of widgets, with a bunch of text, and wait a while before saving, it is bound to come up before long, based on our experience.

In addition, Gary is willing to volunteer to spend time trying to get the bug to happen when he knows the developer is ready to work on it.

**Comment by camillevilla** [comment]
We will be adding Javascript console error monitoring to Exhibits this week to provide further insight into this problem:
https://github.com/orgs/sul-dlss/projects/2#card-15066484

**Comment by joshschneider** [comment]
Just wanted to confirm this issue occurred several times yesterday while I was working on the [Becoming Stanford exhibit](https://exhibits.stanford.edu/becoming-stanford/), if it's helpful as an extra data point. As expected, it slowed down my efforts significantly.

**Comment by mejackreed** [comment]
@joshschneider if you run into this again. Would you mind commenting on this ticket with the page and approximate time it took place? We have some new logging in place which will hopefully better diagnose this.

**Comment by jkeck** [comment]
Worked w/ @joshschneider a bit to watch the issue happen.  When the issue was triggered there was no client error was raised and the server never received the data.  From all accounts, the page is always completely unsaved when this happens (e.g. all edits made in a single editing session are lost).  

We've tried to disable asynchronous javascript loading in production to see if that has any positive or negative effect on this issue.  Initial reports are that it has happened at least once since the config change went out to production.

**Comment by caaster** [comment]
Closing as complaints about this issue have ceased.
