### ISSUE TITLE
For translated feature pages, saved headings for embed widget do not display for all items

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1208]
When I tried to save the translated headings for the next-to-the-last TWO images on this page (using the item embed widget), the headings do not display:

https://exhibits.stanford.edu/zh/paci/feature/1878-1902

**Comment by jkeck** [comment]
@caaster the issue that you're running into here is that the widget that you've translated just the title of this widget and left the text blank (notice that the original widgets have both the Title and the Text filled out).

The way the display logic for this block works is that it only goes to the two column display and renders the title+text if text has been supplied (regardless of if a title is present).  I'm guessing that this isn't the actual intent of the block (given the help text) and is most likely something that has been introduced during various refactorings of this code.

It would be helpful to get @ggeisler to weigh in on what we should do.  Should we update the help on the SirTrevor widget?  Should we update the block to render in a two column display if either text or title is supplied?  (One thing to consider is any existing blocks that have data in the  fields that is currently not displaying _[although if that's the case, I'm not sure we care, and those blocks should be fixed]_).

**Comment by ggeisler** [comment]
I think the ideal option is may be a bit more involved (just in terms of needing to rework the HTML a bit). Looking at some examples of this widget, it often doesn't work too well when text is next it, because the viewer only gets half the width. That should remain an option (in some cases it looks fine having the viewer and text side-by-side, depending on the object used), but I think we should avoid side-by-side when we can, such as if there is only a title and no text.

So, how about we always show the title, if present, above the viewer, and only use the side-by-side layout when there is text? Here's an example where the first instance of the widget is title-only, and the second is title + text:

<img width="450" alt="both-title-one-text" src="https://user-images.githubusercontent.com/101482/42102036-abeed47a-7b79-11e8-8133-1e2ef4a059ec.png">

We should also update the widget intro text. How does this sound?

> This widget embeds an exhibit item in a viewer on a page. Optionally, you can add a heading to be displayed above the viewer and/or text to be displayed adjacent to the viewer.


Much less important would be to adjust the "Display text" option in the widget configuration to make it more clear that the choice of side applies just to the text and not the title + text. This would involve figuring out how to get the radio button selection moved down to align to the top of the text area:

<img width="564" alt="widget-alignment" src="https://user-images.githubusercontent.com/101482/42102227-28c5ac12-7b7a-11e8-857d-b8f65441efad.png">

If we don't do this part, I don't think it will really be confusing to the user (they'll get the ramifications of the "Display text" choice as soon as they save the widget and see the results) so if it doesn't look like an easy update, we could not worry about it.

**Comment by caaster** [comment]
NOTE: this problem happens for the Embed Widget no matter where it is used. It is not happening only on translated feature pages.
