### ISSUE TITLE
The text for screenreaders for the SUL icon is "Spotlight at Stanford"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#1239]
Shouldn't it be "Stanford Libraries"?

**Comment by ggeisler** [comment]
The link goes to the Spotlight landing page, so the current text seems more appropriate. 

Admittedly there's a bit of a disconnect, in that for sighted users the SUL icon implies that the link will go to something more directly "Stanford Libraries" rather than the Spotlight landing page, but we don't really have this pattern anywhere else and haven't decided it's a problem that requires us to figure out a better pattern.
