### ISSUE TITLE
Can't access unpublished exhibit: http://exhibits.stanford.edu/becoming-stanford

### ISSUE THREAD

**Issue by joshschneider** [sul-dlss/exhibits#1314]
I am an editor for the unpublished Becoming Stanford exhibit (https://exhibits.stanford.edu/becoming-stanford) 

After signing in and trying to access the site this morning, I am getting redirected to https://library-status.stanford.edu. However, Spotlight does not appear to otherwise be down, and I haven't seen any related announcements to lead me to believe this is a broader issue. 

I first encountered the redirect issue two days ago; I had been editing the exhibit the previous day. 

Please let me know if I can supply additional information to help resolve this. 

Josh

**Comment by joshschneider** [comment]
I can now access the site, except for https://exhibits.stanford.edu/becoming-stanford/feature/heraldry, which still has the redirect in place.

**Comment by cbeer** [comment]
Thanks @joshschneider; we've identified the proximate cause of the problem:

With the item slideshow widget, an errors occurs if the curator hasn't selected the primary caption, e.g.:

<img width="1141" alt="screen shot 2018-12-17 at 15 39 11" src="https://user-images.githubusercontent.com/111218/50122556-edde9e00-0211-11e9-94f1-bb83451b1cf9.png">

As you noticed, I manually fixed the home page widget, and I've just repaired the heraldry page as well. The good news is, in these situations, it is only the viewing page that is broken, and you can go into the admin dashboard and fix it up.

We're also working on fixing the root cause, but it's in an upstream dependency and may take some time to get deployed.

**Comment by joshschneider** [comment]
Thanks @cbeer for the manual fix and explanation!
