### ISSUE TITLE
Need year to display for Recent Item Indexing/Site Building Activity on dashboard

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1469]
Year is missing from the following, and is needed to display:
Dashboard - Recent Item Indexing Activity
Dashboard - Recent Site Building Activity

@ggeisler - Devs request your input on what date format should be used

**Comment by ggeisler** [comment]
Goals are:

- Add year to the date/time value
- Maintain easy scanability of the date/time value (minimize line-length variability and prevent line-wrapping)
- Ensure the date/time value is easy to interpret by (mostly non-technical) curators

The current display is easy to scan but lacks the year and I think the time value could be easier to interpret, since most non-technical people in the US don't encounter 24-hour time notation very often. For reference, here's an example of what we currently display:

<img width="735" alt="Screen Shot 2020-01-13 at 10 17 28 AM" src="https://user-images.githubusercontent.com/101482/72276832-0aecc880-35ee-11ea-8611-c9fe952df2ff.png">


### Recommended updates
- [ ]  Add year to the current date portion of date/time value, after the month
- [ ]  Follow the year with "at"
- [ ] Display the time value in 12-hour notation

<img width="735" alt="Screen Shot 2020-01-13 at 9 55 48 AM" src="https://user-images.githubusercontent.com/101482/72276706-cd883b00-35ed-11ea-9d18-32e365dd51b8.png">

This example is for the "Recent Item Indexing Activity" table; the same format should be used for the "Recent Site Building Activity" table.
