### ISSUE TITLE
Enhance the Analytics available on the dashboard

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1556]
There are two possible options for this. One may not be possible, but I'll toss it out just in case, and that is embedding the Google Studio view I create for each exhibit on the Dashboard Analytics page. Example (link may or may not work for some; ask Cathy if you have issues: https://datastudio.google.com/open/1Spq46kqX1R8UfZ41NYdpaiIV_Ya1CPAx). Here is a screenshot of the linked page:
<img width="813" alt="Screen Shot 2020-01-25 at 1 58 29 PM" src="https://user-images.githubusercontent.com/3210225/73127787-cf051c00-3f7a-11ea-8133-90d05e15c8cc.png">
If the embedding option is possible:
1) The Google Studio template would benefit from some Stanford styling, and 
2) Cathy would need to create a page for each existing exhibit (intensive labor up front, but do-able), and
3) When an exhibit stub is created, Cathy would need to create a new Google Studio page for that exhibit

Option two is to enhance the analytics parameters currently provided on the Dashboard Analytics page, to include at a minimum, the analytic categories displayed on the Google Studio page. Including a broader date range in addition to the past 30 days would be best, say for the past year as well.

**Comment by ggeisler** [comment]
@caaster Below are explorations of the two options you suggested above. My conclusion is that while Option one is understandably more appealing from an initial visual and functional perspective, it has UX drawbacks, is more fragile in terms of sustainability, and would require a new technical solution to automate the connection between each new exhibit and its corresponding Google Studio dashboard.

Option two as I mocked up below is probably feasible with some relatively straightforward development work (though a real developer would need to take a closer look before we decide the suggested enhancements are doable).

## Option One
I used a copy of the current overall Exhibits google studio page and updated the theme to use more Stanford-oriented colors. Here's how it could look on the current Analytics page, replacing what is currently there:

<img width="1173" alt="Screen Shot 2020-06-01 at 3 42 36 PM" src="https://user-images.githubusercontent.com/101482/83462468-1e26f600-a420-11ea-9ae8-aaa08da6ec0f.png">

### Drawbacks
- As best I can tell, integrating the Google Studio page into an exhibit page would require us to use the embed or iframe code available from each individual Google Studio page. So we'd need to add a superadmin-only field in the exhibit configuration to enable you to plug-in the exhibit-specific reporting code. Enabling that, and redoing the Analytics page to include an embed or iframe that takes as input that configured reporting code, would take some development work, but is probably feasible.

- More concerning is that because we're embedding an external page, there is no responsiveness to the embedded Google Studio stuff. In other words, it looks good in my mockup because I customized the embed size to a specific desktop viewport width. As that width gets narrower, the Google Studio content does not adjust, so before long it will just extend to the right outside of the visible viewport. It just feels pretty clunky unless you have the exact viewport width on your browser to match the hardcoded embed width.

- I'm also concerned that Google Studio is a little fragile. I visited a page I was working on a couple of months ago and all the connections between the widgets in my dashboard and the underlying data sources were broken. I had to click each widget to reconnect them. You might see the same thing on your Studio pages if you haven't visited them in a while.

- Currently, I believe the Analytics page is in Spotlight, so the basic code is available to any Spotlight implementer (they just need to configure their Google analytics code). If we went with Option One, we'd probably have to override the analytics page in Exhibits, since I don't think we can assume every implementer will go to the trouble of setting up Google Studio pages. Creating an Exhibits-specific analytics page is certainly feasible, but it's another thing we'd be diverging from core Spotlight.

## Option Two
In the mockup below I expanded what we currently show to include some of the statistics that appear on the Studio dashboard that I think might be most useful to exhibit curators. Again, I'd want a real developer to take a closer look before we commit to this, but I believe the additional statistics should be feasible to display using our current API approach.

<img width="874" alt="Screen Shot 2020-06-01 at 3 30 36 PM" src="https://user-images.githubusercontent.com/101482/83463101-e02ad180-a421-11ea-8809-fc675d002655.png">

(I changed the reporting period to 1 year; perhaps we could offer both 30 days and 1 year using some sort of tabbed setup - one tab with the label "30 days" and the other "Past year" - that the user can switch between to see the appropriate version of the page above.)

### Drawbacks
- Mainly, this option omits the graphs (technically possible, but we'd need to use some sort of graphing library, which we don't currently do in Spotlight, so that adds to the technical work required quite a bit), and the interactivity (paging past the top N pages or search terms; again probably not technically impossible, but a new pattern that would increase the development work quite a bit).

**Comment by corylown** [comment]
Blocked by: https://github.com/projectblacklight/spotlight/issues/3050

**Comment by alundgard** [comment]
Logging our decisions from today's meeting:
- Omit blank (empty) searches from the _Most used search terms_ list.
- Replace the _Sessions with search_ metric (unavailable in Google Analytics 4) with _Engagement rate_.

Please let me know if further design attention is needed.

**Comment by dnoneill** [comment]
closed by https://github.com/projectblacklight/spotlight/pull/3123
