### ISSUE TITLE
BL7 upgrade: display BibTeX "feature unavailable" message

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1598]
Possible related to #1597?

Currently on -stage we are displaying the actual BibTeX form to users when they select the Curation > Add items, BibTeX option.

<img width="1064" alt="Screen Shot 2020-01-31 at 1 05 20 PM" src="https://user-images.githubusercontent.com/101482/73570824-5b578900-442a-11ea-9553-5d95c34e2aad.png">

I think we intend to only display this form in Parker, otherwise display what is currently shown in the -prod screenshot above?

**Comment by camillevilla** [comment]
@ggeisler This is caused by exhibits-stage's shared configs settings, not by the BL7 upgrade. Curators should see the feature unavailable message in prod once we ship. I _think_ the original rationale was having a place to allow curators to test drive the BibTeX feature (when we thought there was possible reuse) without disturbing the Parker test environment.

**Comment by ggeisler** [comment]
Okay, great, thanks @camillevilla. I'll close the issue and double-check things work as expected when we move to -prod.
