### ISSUE TITLE
Remove :focus and :hover styling from topbar links

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1647]
It looks like our topbar links get some default BS4 styling applied for the `:hover` and `:focus` states:

`..navbar-dark .navbar-nav .nav-link:hover, .navbar-dark .navbar-nav .nav-link:focus` -> `color: rgba(255,255,255,0.75);`

This results in the link text being a more faint white in those states (more obvious in action than in the screenshot):

![Screen Shot 2020-02-12 at 12 45 40 PM](https://user-images.githubusercontent.com/101482/74376012-37833400-4d96-11ea-8f3c-e5b2c06d420e.png)

I suggest we remove that styling so that there is no change to the font color in those states; we can rely on the existing `text-decoration: underline` for the hover state to indicate to the user that they are hovering on this link.

**Comment by ggeisler** [comment]
Reopened this because I still see the same behavior (on -stage) for the hover and focus states as in my original ticket description:

<img width="430" alt="Screen Shot 2020-02-14 at 5 43 49 PM" src="https://user-images.githubusercontent.com/101482/74578414-ce482000-4f51-11ea-9821-e6bad0bf0976.png">

**Comment by camillevilla** [comment]
@ggeisler There's been some flux on the link states since this ticket was filed. Part of my confusion is that I'm seeing different link--> hover colors between stage and local master. 

### local
`#dbdbdb` --> `#ffffff`
![Screen Shot 2020-02-18 at 11 34 51 AM](https://user-images.githubusercontent.com/5402927/74771320-ca164e00-5242-11ea-9561-7530f5955a2e.png)

### stage
`#dbdbdb` --> `rgba(255,255,255,0.75)`
![Screen Shot 2020-02-18 at 11 35 07 AM](https://user-images.githubusercontent.com/5402927/74771317-c97db780-5242-11ea-9237-27f5d0044f47.png)

Can you clarify: Is the desired color `#dbdbdb` or `#ffffff`?

**Comment by ggeisler** [comment]
@camillevilla `#ffffff`, just like -prod, except we now also show the underline on hover.

The `:hover` state should also use `#ffffff` rather than the `rgba(255,255,255,0.75)` though I'm not sure you have to deal with that explicitly or if it will come for free with the fix for hover.
