### ISSUE TITLE
Custom field labels not bold on Add items,  Upload item form

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1662]
On the Curation > Add Items, upload item page, custom field labels aren't bolded like the regular fields:

![Screen Shot 2020-02-12 at 5 08 16 PM](https://user-images.githubusercontent.com/101482/74392048-c609ac80-4dba-11ea-8e79-960439716b50.png)

**Comment by ggeisler** [comment]
Similar issue on the Curation > Edit Browse Category page, although the "Search parameters" field there also needs to be right-aligned:

![Screen Shot 2020-02-13 at 1 05 08 PM](https://user-images.githubusercontent.com/101482/74478172-a8435280-4e61-11ea-89ec-0f452717fa53.png)

**Comment by camillevilla** [comment]
- The issue with bolded labels has been fixed in both spots in master (and upstream Spotlight isn't affected). 
- Issue with form alignment has been resolved

But I found this issue w// the custom field textareas that I'm going to file a PR for:
<img width="900" alt="Screen Shot 2020-02-13 at 2 18 28 PM" src="https://user-images.githubusercontent.com/5402927/74484788-23126a80-4e6e-11ea-8b3e-4e2148d93b6a.png">
