### ISSUE TITLE
BL 7 - carousel widget styling and cycling issues

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1682]
Carousel widget has more pleasing-to-the-eye “round bubbles” as the carousel moves in prod (https://exhibits.stanford.edu/rare-music) as opposed to the version in stage, which caught my eye because it feels visually jarring to me (https://exhibits-stage.stanford.edu/mss). But even if that is personal preference and could be ignored, the version in stage does not automatically cycle as it should.

**Comment by jkeck** [comment]
The carousel appears to be advancing automatically for me on -stage.  Can you give us more information about your browser in case this is a browser specific issue?

**Comment by caaster** [comment]
Yikes. It truly was not advancing in Chrome Version 79.0.3945.130 (Official Build) (64-bit). I just checked again, and now it IS advancing. Gremlins.

**Comment by ggeisler** [comment]
Regarding the indicators, I do agree with @caaster that the indicators we get from BS4 are not very good, especially in some situations where they can be particularly hard to find/see:

<img width="582" alt="Screen Shot 2020-02-14 at 4 39 00 PM" src="https://user-images.githubusercontent.com/101482/74576687-31818480-4f49-11ea-9227-4636de998637.png">

Part of the problem is that they are thinner so don't jump out at you as much, but we also used to have a gradient background that help the indicators standout a bit more:

<img width="874" alt="Screen Shot 2020-02-14 at 4 48 30 PM" src="https://user-images.githubusercontent.com/101482/74576859-fb90d000-4f49-11ea-9ed3-4a76ece9a297.png">

And they were white versus the new dark color. Although you never know what the background of the image is going to be like, it does seem that for our content, a white indicator is more likely to be visible than a dark one. The exception is when the image doesn't take the full width of the viewer as in the example above, but that's where the gradient background helped.

So... as much as I'd like to stick to what we get from BS4 for simplicity, I do think we should try to improve the styling of the carousel. I'll defer to @caaster as to priority (it's definitely not a blocker in my mind) but if we could get it closer to what is currently on -prod I think it would be better.

- [ ] Increase the size of the prev/next controls to `width="36" height="36` (is currently `24`)
- [ ] Use white as the color of the prev/next controls
- [ ] Apply the same or similar styling for the background of `.carousel-control.left` and `.carousel-control.right` in BS3 (background-image and background-repeat properties) to the BS4 equivalent (`.carousel-control-prev` and `.carousel-control-next`)

I can provide more specifics on the styling but that'll take me some time when I can prioritize this.
