### ISSUE TITLE
Slideshow autoplay needs a pause button (or no autoplay)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1775]
Any autoplay feature needs to be accompanied by a pause option. The animation may be too fast for the user to read, or may cause attention/focus issues, etc.

Example here: https://exhibits.stanford.edu/maps-of-africa/feature/cape-of-good-hope?page=8

Option 1:  Add a pause/play button to the dialog

Option 2:  Remove the autoplay and allow the user to control next/previous themselves.

Without knowing all the use cases for this feature, I would be in favour of option 2, but would like @ggeisler and @caaster to weigh in.

**Comment by jkeck** [comment]
Looking into this a bit, the slideshow currently pauses when the user hovers their mouse over the slideshow area.  This is something that is not usable by a keyboard-only user, and also ends up introducing some complications in adding pause/play buttons (e.g. if a user pauses the slideshow using an explicit control and then mouses over the slideshow it will start resume playing due to the current mouse enter/exit behavior).

If we did want to add the buttons, we may want to consider removing the current mouse enter/exit functionality.
