### ISSUE TITLE
Search across: "Start over" button should redirect to site home

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1814]
@jvine correct me if I'm not thinking about this correctly, but when you do a search across search and select the Start over button from the results page, my thought was that we'd redirect the user to the site home/landing page. Currently it seems to just clear your current search constraints and keep you on the search results page.

I guess because of the current behavior, the Start over button is also removed when the user removes all the active search constraints. That's consistent with the idea that the Start over button is just a shortcut for clearing all constraints, but if we decide that the Start over button should redirect to the site home, then I don't think we should remove the Start over button at all (since its purpose is to give the user an obvious way back to the site home/landing page).

I suppose the answer to this is dependent on whether we consider a user who has started a search to only be interested in search (thus we keep them on the search results page no matter what), or if we think the user might just be searching to see what they get but might also still be interested in browsing the landing page cards. I've been thinking about things like the latter scenario.

**Comment by jvine** [comment]
Within an exhibit, in SearchWorks, Arclight, Earthworks:
- if you enter a search term or any constraints, you get a Start over button
- that button goes to the home page (of the exhibit, SW, etc.)

So search-across is a departure from this pattern. I agree that Start over should go to the home page here, and not just clear the constraints.

In EarthWorks, but nowhere else:
- if you do an _empty_ search, you get a Start over button
- it goes to the home page

It's interesting. Technically it's the same as a Home button - it's functionally redundant. In a way, clearing the constraints might be a more logical thing for it to do, but I'd want to test it with users before making this kind of change, because I do think it should be consistent behaviour across our applications.

**Comment by ggeisler** [comment]
For search across, we're agreed that the following change should be made:

- [ ] Selecting "Start over" from the search across results page should redirect the exhibits landing page
