### ISSUE TITLE
[exhibits/prod] ActionView::Template::Error: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#1865]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/61520831)

**Comment by jkeck** [comment]
These seem to always be bots hitting this URL.  I don't see us generating the URL in our markup, so not sure how they're getting to it.  Since we don't have the citation tool enabled, the dynamically defined action is never created so we're just rendering the `citation` view/partial w/o any action backing it up (e.g. no `@documents` ivar is created).  projectblacklight/blacklight#2271 would stop this error from occurring (although getting this to throw a proper NotFound error would take more work upstream)

**Comment by corylown** [comment]
This error [hasn't occurred in 4 years](https://app.honeybadger.io/projects/49092/faults?q=component:spotlight/catalog%20action:citation) and may have been fixed by https://github.com/projectblacklight/blacklight/pull/2271
