### ISSUE TITLE
Editing of About page fails for https://exhibits.stanford.edu/station/about/contacts

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1873]
Issue reported by Donald Kohrs, who is building this exhibit. I have validated this issue. When I try and edit and then save, I see the following error message:

![Screen Shot 2020-04-24 at 10 05 06 AM](https://user-images.githubusercontent.com/3210225/80238779-e1433480-8613-11ea-90a2-8d5e8d2535f3.png)

**Comment by camillevilla** [comment]
More honeybadger info for investigation: 
https://app.honeybadger.io/projects/49092/faults?sort=last_seen_desc&q=request.url%3A%22%2Fstation%22%E2%80%81-is%3Aresolved%E2%80%81-is%3Aignored%E2%80%81

**Comment by camillevilla** [comment]
Hi @caaster! We took a look at this today. 
1. We have manually remediated the data in the Hopkins exhibit to unblock curators there. Though the page has the title "Contacts", its underlying slug is now "hopkins-contacts".
2. We have discovered that About pages cannot be named "Contacts" or have the slug "contact". Trying to edit the page causes a conflict when new data is sent to `about/contacts/edit` because this route is also used when updating exhibit contacts! 
3. I will be filing an ticket (TODO: 🎟) about this in upstream Spotlight. The team is in agreement that this behavior should be fixed, but don't currently have the bandwidth to select a solution. For now, please advise curators not to name their about pages "Contacts".

**Comment by caaster** [comment]
Hi @camillevilla -- thank you so much for investigating; will follow your instruction.
