### ISSUE TITLE
Ensure "per_page" options stay in same order

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1941]
In Exhibits we seem to have different behavior in the search results per_page menu than with Blacklight or even Spotlight. The difference is we display the currently selected option at the top of the list of options, instead of keeping the list of options in a stable order.

In the examples below, the user has selected a per_page option other than the default of 10:

## Exhibits
<img width="274" alt="Screen Shot 2020-10-15 at 2 22 58 PM" src="https://user-images.githubusercontent.com/101482/96192443-e31eee00-0efa-11eb-8c7a-332942d34082.png">

## Spotlight
<img width="228" alt="Screen Shot 2020-10-15 at 3 22 13 PM" src="https://user-images.githubusercontent.com/101482/96192463-ed40ec80-0efa-11eb-8363-2edb1ce9f3c0.png">

## Blacklight
<img width="357" alt="Screen Shot 2020-10-15 at 2 20 25 PM" src="https://user-images.githubusercontent.com/101482/96192490-fe89f900-0efa-11eb-8224-157a9697f6ed.png">

Since the active option is highlighted in the select itself, I'm not sure there's a good UX reason for doing it like we are in Exhibits, and if possible we should maintain the order of the options in the pull-down, as Spotlight and Blacklight do.

**Comment by jkeck** [comment]
FWIW, I believe this is an issues in Spotlight as well, but it is only present/visible when the exhibit has changed the default per page option.

<img width="1155" alt="Screen Shot 2021-02-08 at 1 44 02 PM" src="https://user-images.githubusercontent.com/96776/107285385-edb64380-6a13-11eb-8cd1-f966a2898ce8.png">

This is coming from the following code in Spotlight: 

https://github.com/projectblacklight/spotlight/blob/1c2dc07982c1ebc45f96bca25ed79d32e2ea1ef9/app/models/spotlight/blacklight_configuration.rb#L189-L192

This is removing the configured default_per_page option from the configured per_page options and placing it at the beginning.  This was done, I believe, because Blacklight will use the first per_page option as the default:

https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/configuration.rb#L215-L217

I have a possible change that could address this and will investigate it further.
