### ISSUE TITLE
"More" link in facet doesn't resolve to expected modal window

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1953]
I noticed this myself a little while ago and since then we've received feedback from a user noticing the same thing.

<img width="977" alt="Screen Shot 2020-11-06 at 2 46 23 PM" src="https://user-images.githubusercontent.com/101482/98420344-37257a00-2044-11eb-940e-3baafff1429d.png">

**Comment by jkeck** [comment]
I think this has something to do with some of the view component refactors upstream in Blacklight (but I'm guessing is particular to Spotlight).

The error is ultimately bubbling up from `Blacklight::FacetFieldPaginationComponent#sort_facet_url`.  

In troubleshooting locally I am able to get things to work properly if, instead of calling just `sort_facet_url` if we pass the value of that to `view_context.url_for` (e.g. `view_context.url_for(sort_facet_url('index'))` it seems to work out (which is odd because calling `url_for` w/o `view_context` is more-or-less what's happening and does not work).

**Comment by jkeck** [comment]
And it looks like this was already fixed upstream projectblacklight/blacklight#2381 and will get fixed in the next Blacklight release.

**Comment by jkeck** [comment]
We cut this release today, and will push it out with our patches on Monday.
