### ISSUE TITLE
Display for the search results widget shows text on top of image thumbnails

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2040]
Reported by Sarah Seestone for the Monterey Jazz Festival exhibit, on the following pages:

- https://exhibits.stanford.edu/mjf/feature/festival-posters
- https://exhibits.stanford.edu/mjf/feature/festival-programs

I have verified this issue is not exhibit specific, please see:

- https://exhibits.stanford.edu/cathy-test-exhibit/feature/test-page-6

**Comment by ggeisler** [comment]
Here's more info in case it helps.

At least for the MJF example, it seems to matter if you are authed or not. For example, on both Firefox and Chrome I see a difference when I logout versus when I'm logged in:

## Logged in - looks fine
<img width="856" alt="Screen Shot 2021-03-13 at 11 33 48 AM" src="https://user-images.githubusercontent.com/101482/111040704-924fea80-83f1-11eb-969c-cc4def67921b.png">

## Logged out - thumbs smaller, IIIF icon present, fields overlap with thumbnail
<img width="887" alt="Screen Shot 2021-03-13 at 11 34 14 AM" src="https://user-images.githubusercontent.com/101482/111040730-aeec2280-83f1-11eb-80a1-6ae1273bd545.png">

---

It does appear that this is specific to the Search results widget's gallery view, not search results gallery view in general. I indexed a few of the items from the exhibit above into my test exhibit and they look fine in search results gallery view, both when I'm logged in and when I'm logged out.

Furthermore, I thought that this was somehow specific to the MJF exhibit, because I added a search results widget to my test exhibit, which includes several of the MJF items, and it looks fine, whether I'm logged in or not. But @caaster's example maybe indicates another condition might be whether there are metadata fields included in the view, though in my example I did include the Collection field and it looks fine:

<img width="887" alt="Screen Shot 2021-03-13 at 12 22 05 PM" src="https://user-images.githubusercontent.com/101482/111041710-d2659c00-83f6-11eb-81ed-4775c3ca5cc6.png">

---

I also tried replacing the search results widget (with one that is based on the same underlying search result set) in the MJF Festival Posters page and it shows the same problem.
