### ISSUE TITLE
Index (and provide the ability for display) of custom metadata fields for wong project, "provenance" and "exhibition history"

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#2050]
In a similar approach to custom Parker metadata fields, this ticket  needs to be able to index provenance and exhibit history into fields.

### dy529tn0614
```xml
<note type="ownership" displayLabel="Provenance">
The Artist The Estate of Martin Wong/ P.P.O.W, 1999 Galerie Buchholz Private Collection, 2010
</note>
<note type="exhibitions" displayLabel="Exhibition history">
"Martin Wong: Works 1980-1998," Galerie Daniel Buchholz, Cologne, May 28 - August 22, 2010 "Martin Wong: Works 1980-1998," Galerie Daniel Buchholz, Berlin, August 27 - September 25, 2010 "Taiping Tianguo, A History of Possible Encounters" Para Site Art Space, Hong Kong, May 12, 2012 - Aug 28, 2012 "Julie Ault/ Heinz Peter Knes/ Danh Vo/ Martin Wong: Neptune Society, San Francisco Columbarium, 4th FL, Dome Room, South Wall, Tier 4, Niche 2," Galerie Buchholz, Berlin, November 30, 2012 - January 19, 2013 "Taiping Tianguo, A History of Possible Encounters," SALT, Istanbul, May 8 - August 11, 2013;
</note>
```

These should be able to be displayed using the same logic `paragraph_joined_content` and would expect the metadata to include line breaks or individual elements.

Note: `provenance` `<note>`  was added already in https://github.com/sul-dlss/exhibits/pull/2037 but only as part of `<physicalDescription>`

**Comment by caaster** [comment]
The Wong Team's request in this vein was misunderstood. They do not want what this ticket specifies, so I am closing this ticket. Email explanation provided below:


From: martin-wong-project <martin-wong-project-bounces@lists.stanford.edu> on behalf of Catherine A. Aster <caster@stanford.edu>
Sent: Tuesday, July 6, 2021 1:25 PM
To: martin-wong-project@lists.stanford.edu <martin-wong-project@lists.stanford.edu>
Subject: [martin-wong-project] Following up re Provenance and Exhibition History on the PURL
 
Hi All,

I've checked in again with Arcadia regarding the Wong QA team request to provide an alternative solution if possible to the current display of metadata fields Provenance and Exhibition History so that they are not included under the heading Bibliographic information.

I want to thank the QA team for spending time this morning to make sure I fully understood this request, one last time. For the maintenance, sustainability and future migration of all item metadata in Stanford Libraries systems, supported by adherence to metadata best practices and standards, we are not able to make the changes you have requested. We understand that this will be cause for disappointment. The proposed Research Guide About page in the Martin Wong Catalog Raisoneé can be used if desired to clarify the placement of descriptive metadata on the PURL page, if this would be useful to researchers.

We hope that our ability to be flexible in other ways, including offering valuable options for researchers such as transcript downloads and full text search -- serve as a positive counter-balance for this important project. The passion of everyone's engagement continues to be a source of inspiration.

Best regards,
Cathy

Cathy Aster | Services Manager
Spotlight at Stanford | Electronic Theses & Dissertations
DLSS Liaison to SERG, Preservation, Map Projects & GIS
https://library.stanford.edu/people/caster
Stanford Libraries | Digital Library Systems & Services

mobile: 650.619.3930
Orcid ID: 0000-0002-4943-2942
pronouns: she/her/hers
