### ISSUE TITLE
Not all images are going through preprocessing steps

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#2057]
This is causing unnecessarily large images to slow down pages:

https://exhibits.stanford.edu/uploads/spotlight/attachment/file/4998/Screen_Shot_2020-08-27_at_1.01.41_PM.png

on

https://exhibits.stanford.edu/maps/feature/finding-useful-maps

2832x1366 6.59MB image being displayed at approximately 370px.

And looking at timestamps this might have already been uploaded.

**Comment by caaster** [comment]
@mejackreed happy to work with exhibit creators on this. Is it feasible to provide guidelines on size recommendations? I know we have a limit on images of max 10 MB, but it sound like we may need to revisit this?

**Comment by ggeisler** [comment]
@caaster @mejackreed Perhaps in addition to the 10 MB max hint text (which was intended to prevent the really outrageous cases more than encouraging _ideal_ image sizes for optimal page loading speed), we could add a max dimensions recommendation to the upload form component. For example, for the page thumbnail, we never display it at wider than 290px, it appears. So we could add a recommendation to the form (I'm saying 400px here just to make it a little future-proof):

<img width="1009" alt="Screen Shot 2021-03-29 at 2 22 27 PM" src="https://user-images.githubusercontent.com/101482/112902525-187b5a80-909b-11eb-984b-f1034874be70.png">

---

The only challenge with this approach is we'd need to customize the additional text (the part underlined in red above) for each context where we offer this form, because the context determines what the optimal max size of the image is (e.g., we wouldn't want to say 400px max on the exhibit masthead version of this form).

Of course, we might also want to update the documentation exhibit with similar context-specific max dimensions guidance.

**Comment by ggeisler** [comment]
@mejackreed I've added some caveats about image size for different contexts to the exhibits documentation pages (rather than the approach of adding help text to the UI as I suggested in my prior comment).

I'm not sure if there is anything else technical we need to investigate before closing this?

**Comment by mejackreed** [comment]
Go for it, we can close
