### ISSUE TITLE
Consult/info needed re SITE exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2078]
There is an exhibit stakeholder (SITE staff, Sharyn) that we created this exhibit for: https://exhibits.stanford.edu/site-archive

Sharyn is excited about the new browse group feature in exhibits. She asked if browse groups could be created for the content in this exhibit, according to session -- which is contained in the metadata.

It turns out that there are 207 sessions, and that number will grow. Browse groups is therefore not the right solution.

Here is some additional information from Sharyn about the sessions for the items in the exhibit:

-  Are sessions captured in the descriptive metadata for each paper?
Yes. There are two metadata sheets: 1) the main (1993-present) template, which contains all the sessions and 2) the digitized papers (1990-1996) template, which contains no sessions.
- Are sessions discrete for each year, or do they cross multiple years?
Some sessions cross multiple years.
- Does each paper only have one session, or could it be assigned to multiple sessions?
The majority of the papers have one session although there may be a small handful that may have been presented more than once at another session.
- Are there any papers that are not in a session?
Only the digitized papers.
- Do you know how many total sessions there are?
207 total sessions from 1993-2020. More to follow with future conferences.

Here is an item in the exhibit with a session: druid:sn380cv1019
![Screen Shot 2021-04-14 at 11 44 03 AM](https://user-images.githubusercontent.com/3210225/114762750-e878bc00-9d16-11eb-9ffc-fcf3576a6d43.png)

I'm trying to avoid the idea of requesting specialized indexing for this exhibit. Instead, I wonder if tagging would be able to address Sharyn's request (this will be tedious indeed, though do-able). We can get lists by druid and session for each item in the exhibit, and using that information we could tag each item with the session name. Then, we could display exhibit tags (rename as "sessions") on the home page. However, in test exhibits with tagged items, I see that tags are displayed in order from the tags with the largest numbers of items to the smallest. It doesn't appear that I can change the sort order to be alphabetical. In other words, I am not seeing the following facet menu for exhibit tags:

![Screen Shot 2021-04-14 at 11 35 44 AM](https://user-images.githubusercontent.com/3210225/114761648-a26f2880-9d15-11eb-998b-9237a5a73d4d.png)

The upshot is, I am searching for the best possible solution for Sharyn and the SITE exhibit. She wants users to be able to search items according to session name.

Using exhibit tags or requesting a custom index/display for this exhibit are the only two possibilities I'm aware of. I'm open to and looking for recommendations.

**Comment by ggeisler** [comment]
@caaster Tagging items by session title and renaming the tags facet "Session" (since tags are not used in this exhibit yet, I'm assuming that using tags only to identify session title would make sense) seems like a viable approach to me. The hard work is just tagging each item appropriately, though it appears that to some degree this could be done with bulk action tagging. For example, I found a paper that was in a session called "Recursive Mechanism Design" and then did a search on `"Recursive Mechanism Design"` and got 15 hits that all might be part of the session (I checked a few and they were). So I could then use the bulk tag action to tag them all `Recursive Mechanism Design`.

Then rename the Tags facet "Session" and the user would see all the different session titles as values in that facet.

There will be at least 10 different facet values, so you will see the "more" link at the bottom of the Session facet, and when you select that link you should get a modal with the A-Z and Numerical sort options.

I'm not sure if we can configure a specific facet in a specific exhibit to sort by title by default or not, but in this case listing the session titles in the facet by count seems acceptable to me.

**Comment by ggeisler** [comment]
@caaster I agree browse groups don't make sense for the goal of organizing by session. 

The existing browse categories are based on conference year, which seems useful. There are kind of a lot of them, so while I wouldn't argue it's a huge improvement or a must-do, Sharyn could add four browse groups to split the existing browse categories by decade:

- 1990s
- 2000s
- 2010s
- 2020s

That could help the user zero in on a specific year a bit more quickly, if they were focusing on a particular time period.
