### ISSUE TITLE
When creating translations for pages, the translated title displays in the "English" column

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2191]
In the Say Their Names exhibit, the following occurs, in this order:

- User logs in to the exhibit
- User selects Spanish from the drop-down menu in the top right-hand corner (same happens with Chinese as stated below...)
- User navigates to Exhibits dashboard > Curation > Translations > Spanish > Pages
- User sees the Spanish name for each page in the "English" column, as you see below:

![Screen Shot 2022-05-23 at 2 49 15 PM](https://user-images.githubusercontent.com/3210225/169911248-471cc476-071f-462e-9f5e-ebda74c43e5d.png)

This is really confusing for the person working on the exhibit. Especially so -- if they are copying and pasting translations for a language they do not read or speak (like Chinese, possibly -- for example).

Desired behavior:
- When in the Translations > Pages tab for any language, the exhibit creator should see the English page names displayed in the left-most column, and not the translated page names.

**Comment by ggeisler** [comment]
It's true that the UI is incorrect in using "English title / last update" for the first column headings in the screenshot above when Spanish was chosen as the display language, but I believe that is because the user is not following the intended translation process. Specifically, I don't understand why the user would do this step:

> User selects Spanish from the drop-down menu in the top right-hand corner (same happens with Chinese as stated below...)

That language menu is to control the **display language of the exhibit**. It is not part of the translation process. 

It sounds to me like maybe there is a misunderstanding of how to use the translation interface. You control which language you are providing translations for in the Curation > Translations page. As shown below, I am prepared to make Italian translations for my exhibit. If I wanted to make Spanish translations, I would select the fourth button that says "Spanish", not change the exhibit's display language.

<img width="888" alt="Screen Shot 2022-05-23 at 3 21 46 PM" src="https://user-images.githubusercontent.com/101482/169914592-6912ff97-354e-4048-9d45-91d3f3ed2021.png">

---

I think enabling the user to change the display language and then provide translations while in that non-English language implies another level of requirements that are brand-new. We designed the translation interface for a user to provide non-English language translations while using English as the display language.
