### ISSUE TITLE
IIIF Drag and Drop broken in Parker on the Web (and potentially across all exhibits and SearchWorks)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#2406]
I realize that this cuts across more than just Exhibits, potentially, so please feel free to move.

Issue: IIIF drag and drop icon appears to be broken across all Stanford platform. Drag and drop no longer works; click-through leads to a "page not found" on the library website; etc. This issue was noticed by a user on the Parker platform.

Expected behavior: 
* ability to drag icon into a IIIF viewer in another browser tab and have the digital object open in that new environment
* click-through - previous behavior was to send the user to a "learn more" page; other institutions implement that in different ways (including opening up the manifest in a new tab in a new IIIF viewer)

Current behavior:
* drag to new tab does not result in opening the object in a new viewer
* click-through leads to "page not found"

**Comment by corylown** [comment]
The page that the IIIF logo links to no longer exists because it was not migrated to the new library website. There is a plan to create a new IIIF page. Once that page exists we can update all the links the IIIF drag and drop feature will resume working.

[References to in our code to: https://library.stanford.edu/projects/international-image-interoperability-framework/viewers](https://github.com/search?q=org%3Asul-dlss%20%22https%3A%2F%2Flibrary.stanford.edu%2Fprojects%2Finternational-image-interoperability-framework%2Fviewers%22&type=code)

**Comment by corylown** [comment]
We've updated the link so that it goes to https://iiif.io instead of the library website page that no longer exists.
