### ISSUE TITLE
Users should not need to log in before being assigned roles

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#32]

**Comment by cbeer** [comment]
I wonder if we can use (and/or check for)  https://github.com/scambra/devise_invitable to provide this behavior/workflow.

**Comment by cbeer** [comment]
Here is where we assign roles to users:

https://github.com/sul-dlss/spotlight/blob/master/app/models/spotlight/role.rb#L24

It seems like we should add another class-level method on `User` (which is generated into and provided by the host application) to give them control over this behavior, maybe:

```
::User.find_or_invite_by_user_key(key)
```

and provide a default implementation (without any invitations or anything) here:

https://github.com/sul-dlss/spotlight/blob/328363720fbee6c4ee997123bb2771434b7859b4/app/models/concerns/spotlight/user.rb#L29-L31

In sul_exhibits_template, we would override `User.find_or_invite_by_user_key` to trigger the devise_invitable logic (or just force-create users, I suppose.)

**Comment by peetucket** [comment]
We should destroy roles associated with a user when the user is destroyed.  Discovered orphaned roles when I destroyed a user on the console.

**Comment by peetucket** [comment]
"Add a new user" button on admin user page should probably say "Invite a new user"

**Comment by ggeisler** [comment]
I see what you mean, but I'd suggest keeping it as "Add a new user." The mechanism by which users are added involves an invitation, but the goal of the admin user who selects the action is to add a new user to the exhibit. It's seems more straightforward to match the button label to the goal of the admin user.

I'm not sure how the invitation action works, but presumably we can show a flash message that says "Invitation sent to peetucket@example.com" or something similar so that the admin understands the action is pending. (Or show a "Waiting confirmation" or similar message under the invited user's name to indicate the status? Similar to how we do the contact email invitation status.)

**Comment by peetucket** [comment]
@ggeisler: In the existing workflow, do you add a SUNET ID only or the full email address?  The implementation in spotlight that jessie started requires an email address to be added for an invitation (which matches the default spotlight login page, which asks for an email address instead of a username).  We may also want to relabel the header on the admin users table from "Username" to "Email" to clarify.

**Comment by ggeisler** [comment]
We add the complete email address. So, yep, good idea, relabel the header "Email address".
