### ISSUE TITLE
Vanity URL's?

### ISSUE THREAD

**Issue by snydman** [sul-dlss/exhibits#398]
Is it possible to create vanity URL's for Spotlight exhibits such that http://exhibits.stanford.edu/[stub] can be http://[stub].stanford.edu??

We want to do this specifically for Parker on the Web which will be migrated to Spotlight by the end of 2017. We want to create it in http://exhibits.stanford.edu/parker but have it resolve with all sub-ages to http://parker.stanford.edu.

JIRA SAR has been created at https://jirasul.stanford.edu/jira/browse/SAR-3334 for cross reference with Sys Team.

@tomcramer @blalbrit are interested.

Questions to answer:

- What is the right way to do this?
- What is the effort level?

**Comment by cbeer** [comment]
With the caveat that anything is possible with enough time and resources to develop and maintain it:

- It is trivial to have parker.stanford.edu and exhibits.stanford.edu resolve to the same site.
- It doesn't seem possible to allow self-service subdomain creation, given all the systems-side work necessary to support that.
- I'm not sure it's reasonable to use vanity urls in place of the exhibit id parameter in the url (meaning supporting e.g. `http://parker.stanford.edu/catalog/` instead of `http://parker.stanford.edu/parker/catalog`). At this point, trying to support both vanity-url-based and path-based routing probably means mucking with Rails internals in dangerous ways. In hybox, we've supported only vanity-url-based routing, so that much is possible, but having them both co-exist seems very challenging.
- That said, if duplicating `/parker` in the path is acceptable, it doesn't seem unreasonable, but would need additional work, to prevent visitors to `parker.stanford.edu` from seeing the exhibits index page or viewing other exhibits while in the parker context.
- If that's unacceptable, perhaps it is possible to create an additional exhibits application (perhaps even using the same code with some feature flags) and deploy it to a different environment that only supports vanity url backed sites. I'm not sure, though, how we'd handle integration with things like the exhibits.stanford.edu index page.
- Perhaps there's a proxy-based solution the systeam can comment on, but it strikes me as unlikely or unpleasant to maintain given the mix of exhibit-context and non-exhibit-context paths in use.

**Comment by blalbrit** [comment]
@cbeer  duplicating `/parker` in the path is acceptable.

**Comment by blalbrit** [comment]
@rsmith11 has this set up. temporary proxy at http://parker-proxy-lb.stanford.edu will change to parker.stanford.edu on Jan. 10 for launch.
