### ISSUE TITLE
Create Mirador (sir trevor) widget

### ISSUE THREAD

**Issue by snydman** [sul-dlss/exhibits#415]
Create a widget that allows an exhibit creator to embed a Mirador instance that displays a particular image, or image comparison set, and allows viewing of annotations for that image or comparison set.  

Essentially, embed Mirador on a feature page in a certain state.   

@blalbrit 

ps - should this be a SUL-Exhibits ticket or can this be a generic widget in Spotlight?

**Comment by blalbrit** [comment]
Open question - should this be in the general Spotlight repo instead?

**Comment by mejackreed** [comment]
I would vote not to make mirador a dependency of Spotlight. Are we able to embed an already hosted version of mirador in an iframe? or do we need to serve our own?

Potentially could use https://github.com/jeffreycwitt/mirador-rails to bridge some of this?

**Comment by blalbrit** [comment]
Initial assumptions:
* the iframe approach is unfeasible here as the Vatican team will want to be creating a number of different configurations of workspaces to tell their stories (see next comment for other iframe issues) - suggest a widget with the following requirements:
** user can choose workspace layout (though perhaps with a smaller range of options than full Mirador layout options due to screen real-estate)
** user can choose one or more manifests to populate that layout
** user can choose one or more specific pages for the workspace view
** user can choose to turn off thumbnail strip (? - or do we restrict that off the bat for design considerations)
** user can choose to have the annotations configured on or off
** can the user specify the zoom level for initial load (? open question for team)
* to begin with, objects must be in the exhibit already in order to be loaded into the Mirador widget so as to avoid the https/http conflict (see below) - unless there is an easy technical work-around for that conflict

**Comment by blalbrit** [comment]
Example of manually configured Mirador instance (http://dms-data.stanford.edu/data/m22/dragmaticon_comparison1.html) with:

- 4-up layout
- mss. from Stanford, e-codices and BNF (Stanford = https, other two are http)
- configured with the thumbnail strip turned off

![screenshot 2017-03-09 11 53 25](https://cloud.githubusercontent.com/assets/796990/23767911/23dec7ac-04bf-11e7-9ab8-c20e77c86e8e.png)

Same example embedded in iframe in Spotlight:

- note loss of two http institutions from layout
- certain issues with screen real-estate

![screenshot 2017-03-09 11 53 38](https://cloud.githubusercontent.com/assets/796990/23768015/731a9364-04bf-11e7-9a07-98185ac7eb32.png)

**Comment by ggeisler** [comment]
Restricting items that can be used in the widget to only exhibit items -- even if that's just a temporary restriction -- makes this pretty straightforward (the design, at least), I think.

Selecting the Mirador widget works like any other exhibit item widget: we'll add the widget button icon to the widget selection panel:

![widget-panel](https://cloud.githubusercontent.com/assets/101482/23925176/411b98c6-08cb-11e7-9cb6-95a1222b12f1.png)

(I'll provide an image for the icon and recreate the .svg file that is used for the panel.)

### Configuration
The mockup below follows the same pattern as our other widgets that accept multiple exhibit items. However, the options are different in that we don’t need to give the curator the option of captions and I think we want to place the optional text in a block _above the viewer_ and not adjacent to it.

![mirador-widget-configuration-v2](https://cloud.githubusercontent.com/assets/101482/23926614/5998f37e-08d2-11e7-80c8-53de9e2ea407.jpg)


Here’s the instructions text:

> This widget displays exhibit items in a Mirador viewer, which enables exhibit visitors to view and compare images in a zoomable, interactive environment. Optionally, you can add a heading and/or text to be displayed above the viewing environment.

The viewer layout select box enables the curator to select layouts ranging from 1x1 to 2x3. After experimenting a bit, I think 3 across could work fine, especially if the page has no sidebar, but more than 2 rows seems too tall to be very useful. However, we could adjust that after we get it implemented and see how it feels at different sizes.

![mirador-widget-configuration-select-layout](https://cloud.githubusercontent.com/assets/101482/23926109/b2efb6f4-08cf-11e7-91f2-d2e83b0de676.png)


I’m not sure how things will look with item annotations and/or the thumbnail strip enabled, but those two options seemed worth trying out.

As with other widgets, if the curator selects more items than fit the layout, the extra items are ignored. If the curator doesn’t select as many items as the layout allows, I think we can just leave the extra cells empty and assume the curator will see the issue and adjust accordingly.

When saved, the widget should look pretty similar to @blalbrit's example above (though ideally if an item isn't available for display for some reason, I don't think we want to show the +Add item since I assume that wouldn't work in this context).

**Comment by blalbrit** [comment]
Note: additional requirement = Lockable Zoom Level

**Comment by aeschylus** [comment]
Can you say more about lockable zoom level? Is this a user control element, or a curator configuration? I know Jeff Witt implemented a zoom locking button of some kind for his workflow.

**Comment by blalbrit** [comment]
The desire, as expressed by the Vatican team, was that a curator would choose the zoom level for the specific comparison they were presenting in the widget, and be able to lock that so that every time the page with the widget opened, the starting state would be their chosen zoom @aeschylus

**Comment by ggeisler** [comment]
@aeschylus So is there any way for a user to save a IIIF URL that includes the current zoom level state of the item?

I'm trying to understand if there is a way to satisfy the Vatican desire shared above by @blalbrit to present an item in the Mirador widget that loads at a specific zoom level.

I could see an approach where the curator zooms to a desired zoom level in the widget configuration and we save that (e.g., select an item, when the widget box for the panel for the selected item loads give them a zoom control in the panel to change the zoom level) but that would likely be pretty complicated (both technically and from a UX point of view) to do in the widget configuration panel. (And, I think, would also require that this zoom level of the configured item is saved when the widget configuration is completed and the page is saved.)

**Comment by aeschylus** [comment]
And thanks @blalbrit for clarifying. We want to make sure zoom is saved and restored with any other state the curator has in their mirador instance for presentation.

**Comment by ggeisler** [comment]
Okay, thanks @aeschylus. Let's discuss more 1:1.

**Comment by ggeisler** [comment]
Because the revised design for this feature is fairly involved and different from what was presented here, I've created a [new ticket](https://github.com/sul-dlss/exhibits/issues/1002) for the new design and am closing this ticket.
