### ISSUE TITLE
Show map displays broken image

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#436]
See example here:
https://exhibits-stage.stanford.edu/lanciani/catalog/yr003vy0538

**Comment by jkeck** [comment]
I think axyjo/leaflet-rails#63 is related

**Comment by jkeck** [comment]
So that PR looks promising in that it does the thing that should generate the appropriate url for the maker icon, however it has been sitting around since Dec. (and the maintainer has indicated reluctance).

So we can either live w/ the broken marker icon or we can run directly from the fork that makes that PR.

**Comment by jkeck** [comment]
Also, just for those following along, the broken link is the marker-icon.  This is what we would expect.

<img width="634" alt="marker-icon" src="https://cloud.githubusercontent.com/assets/96776/22842813/8175ffe6-ef8b-11e6-9e4f-921569972568.png">
