### ISSUE TITLE
Design support for external bibliography service

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#441]
Requirement for Parker:

- bibliography entries maintained in an external service
- bibl entries tagged to associate them with relevant mss. in Parker
- Spotlight needs to be able to query the external service and build a bibliography view within the item view

Sub-tasks:

- [x] UX design
- [x] technical requirements

**Comment by ggeisler** [comment]
Below is a first pass at how we might do this, intended to start a discussion of some of the details and assumptions we'll need to decide on before this is an actionable ticket.

The first assumption is that there is a service endpoint that accepts an object druid and returns a set of bibliography references that match that druid. So when a visitor in an exhibit navigates to an item show page:

- If the exhibit is configured with a valid service endpoint, druid is sent to the service
- If the endpoint returns a non-empty set, the returned set of items is parsed and displayed as list items in a named section at the bottom of the item details page

Generically, something like this:

![bibliography-concepts](https://cloud.githubusercontent.com/assets/101482/23326847/439fc770-fac0-11e6-9437-e1e160ba0cd8.png)

Where the configuration might look something like:

![configuration](https://cloud.githubusercontent.com/assets/101482/23326443/e5889d4c-faba-11e6-8445-5be09269547c.png)

And the populated item details page like this, with the Bibliography section in a new row below the metadata (Parker items have very long lists of refs, so this feels like the best way to show them):

![bibliography-mockup](https://cloud.githubusercontent.com/assets/101482/23326452/f4e35ac0-faba-11e6-8bdb-9c66f22e97f0.png)

### Other assumptions
The configuration mockup above assumes the service is a bibliography service and the key value sent to the service is a druid, but by requiring the exhibit admin to enter the service endpoint (and allowing them to override the section heading) I believe we'd be leaving it generic enough that exhibits other than Parker could theoretically set up their own bibliography service endpoints and use the feature. So it's not Parker-specific but it is _bibliography_ specific (or at least, _service that provides a set of items we're going to display as a list_ specific).

For Parker the above assumption is probably fine, but thinking more broadly: do we want to make it even more generic? It could just be an "Item Details page" service and we display whatever is returned from the endpoint. But that would require a more complex configuration, such as what HTML tags to wrap the returned values in, how to sort them, whether what's returned is even a set of items versus a single item, etc. 

Although the mockup doesn't show it, ideally the bib service would store the references HTML-encoded, so we retain the proper reference formatting. The service should also be able to return the set of refs sorted alphabetically.

**Comment by blalbrit** [comment]
If we're going to go with Zotero for the bibliography service, see:
https://www.zotero.org/support/dev/web_api/v3/basics
and
https://library.brown.edu/cds/2015/06/29/zotero-api-web/

I believe the simple return for a formatted bibliography list caps at 150 objects, which might be a problem for some of the objects in this collection. I believe, though, we can get a larger return if we just take json back - which would then require formatting in Spotlight, but would get us around the issue of number-of-item caps.

**Comment by drh-stanford** [comment]
I dug into the API and below is some rough code that does what we want -- assuming we have a Zotero collection to export. And the 150 item limit is correct.

```ruby
n = 0
done = false
puts '<ul>'
until done do
  url = "https://api.zotero.org/users/#{USER_ID}/collections/#{COLLECTION_ID}/items" + '?' +
        URI.encode_www_form(v: 3,
                            format: :json,
                            include: 'bib', # or 'data,bib' if you also want Zotero data in their schema
                            key: API_KEY,
                            start: n,
                            limit: LIMIT)
  open(url) do |conn|
    items = JSON.parse(conn.read)
    if items.empty?
      done = true
    else
      items.each {|item| puts '<li>' + item['bib'] + '</li>'}
      n += LIMIT
    end
  end
end
puts '</ul>'
```

**Comment by drh-stanford** [comment]
## Open Issues

1. How does the exhibit user associate an item (key = druid) to a Zotero Collection?
   - They could name the Zotero collection after the druid (or maybe use the exact title if Zotero support the same naming conventions)
   - They could drop the Zotero collection URL into a Spotlight Item field
   - Or, ...?
1. How does the exhibit user authenticate into Zotero? Or do we force exhibit users to make their bibliographies public as authentication is not required for read access to public libraries.
1. How do we handle Zotero API outages?
1. Do we support Zotero "groups" or only "users"?
1. Do we support Zotero's nested collections and nested items data model?
1. What specific citation style and sorting do we want to use? The default is Zotero's "`chicago-note-bibliography`" that sorts by Author-Date.

## User Data Needed

1. The "Service Endpoint" would always be `https://api.zotero.org/users/#{USER_ID}` so the data requires is the Zotero user id.  To get this id the exhibit user will need to copy it from the Zotero "API" section of the "Settings" interface.

## Bibliography service

We will use [Zotero](http://zotero.org) as the bibliography database, and they have a public [Web API](https://www.zotero.org/support/dev/web_api/v3/start) (though I couldn't find an existing Ruby gem that supports it). Note that there's a 150 item limit per Zotero collection if we use their styling engine.

**Comment by blalbrit** [comment]
In checking the current data, many of the Parker objects have a bibliography in excess of 150 objects, so I think we'll need to pull the raw JSON back (which allows more than 150 objects). That gives us the opportunity to determine our style output more freely.

I would be fine with using the same styling we currently use in Parker on the Web (see here for exx. https://parker.stanford.edu/parker/actions/bibliography_search_results.do?
journal=&primarySourceRef=286&author=&title=&sort=alphabetic&shortTitle=&comment=&date=&referenceTypes=) less the comments/reproductions links.

**Comment by blalbrit** [comment]
For Parker, specifically, for:
How does the exhibit user authenticate into Zotero? Or do we force exhibit users to make their bibliographies public as authentication is not required for read access to public libraries. Alternatively we need to have their Zotero API key (and possibly need to do OAuth).

This will be a public bibliography.

If we want to generalize this for general Spotlight, this could be revisited - but the requirement for Parker is simply to support a public collection.

**Comment by blalbrit** [comment]
How do we handle Zotero API outages? e.g., we're seeing 503 errors today on their API.

I think a simple user-message would be acceptable on a 503 "The bibliography service is not currently available" or something similar. @ggeisler - do you have preferred wording for something like this?

**Comment by blalbrit** [comment]
What specific citation style and sorting do we want to use? The default is Zotero's "chicago-note-bibliography" that sorts by Author-Date.

See above for style.

For sorting, Author-Date is perfect.

**Comment by drh-stanford** [comment]
Re: style. I don't recognize that bibliography style in the mockup. Does it have a name, or is it a custom style for the Parker community? Ideally, the style we want has a [CSL implementation](http://citationstyles.org) available in their [repository](https://github.com/citation-style-language/styles). Right now it looks like Parker is doing an entirely custom Java-based styling (see https://github.com/sul-dlss/parker-webapp/blob/acfe1a98d6d39bd3a044606344882dff85977b4e/WEB-INF/src/edu/stanford/sulair/parker/search/BibliographySearchResult.java)

**Comment by blalbrit** [comment]
Yes - the Parker style was tricky as we were going between British style guides and American. Let's go with Chicago now (author-date).

**Comment by drh-stanford** [comment]
For the open issue on how to associate exhibit items with bibliography items, we can use Zotero tags. The exhibit user would need to add the druid to the tag list for all the items.

You can search the library by TAG like so: `https://api.zotero.org/users/3802090/items?tag=druid:iouoiuoiuo`

**Comment by drh-stanford** [comment]
Ok, I've written up a technical requirements doc here -- https://gist.github.com/drh-stanford/ffa984205f406d6267e5fa8e2606ee68. This needs some review...

**Comment by ggeisler** [comment]
Based on the work and comments from @drh-stanford, @blalbrit, and @jkeck above and in the referenced gist, below is an updated mockup of the configuration page. This might need further tweaking as the feature is developed, but is closer to what'll be necessary in the UI to support the implementation @drh-stanford proposes.

(In the instructions I tried to use terminology that would be familiar to a Zotero user, but since I've never used Zotero, there might be better ways to word it. If anyone is more familiar with Zotero and has better ideas, feel free to update my wording.)

![configuration-v2](https://cloud.githubusercontent.com/assets/101482/23524206/7954d3e2-ff3e-11e6-8bc8-2028277739ae.png)

For copy and paste purposes, here are the text strings used in the form:

> If items in this exhibit have bibliography references associated with them in a Zotero library, the application can display the associated references when an item’s detail page is displayed. The Zotero library must be a public, single (non-nested) collection of reference items in which each item is assigned a separate tag (e.g., “gh328kv5465”) for each druid associated with it. When an exhibit visitor navigates to an item details page, all Zotero references tagged with the item’s druid are displayed in a named section at the bottom of the item details page.

> See the API section of the your Zotero library's settings for your user or group ID.

**Comment by ggeisler** [comment]
@blalbrit Regarding your earlier suggestion about wording when the Zotero API is not available, your suggestion of "The bibliography service is not currently available." sounds fine to me.

**Comment by drh-stanford** [comment]
Talked with @blalbrit and @mejackreed and we're going to investigate a "Sync with Zotero" workflow that would be in the Exhibits Settings that the curator updates regularly. This simplifies the implementation somewhat and avoids the delay when viewing exhibit items.

**Comment by drh-stanford** [comment]
I've updated that requirements doc to use the "Sync with Zotero" workflow. We need some UX updates to implement it. Note that I've also added a couple more open issues.  https://gist.github.com/drh-stanford/ffa984205f406d6267e5fa8e2606ee68

**Comment by ggeisler** [comment]
@drh-stanford @blalbrit @mejackreed @jkeck Updated mockups below. Let me know if you think I'm missing anything or if you have concerns or suggestions.

All mockups below reflect the addition of a "Synchronization status" section at the bottom of the form to deal with the synchronization requirement. The rest of the form is unchanged from my previous mockup described in an earlier comment.

### First-time configuration
If the exhibit has not yet been successfully configured with a Zotero library, the Synchronization status section should show a text message that reflects the never synchronized state and hide the synchronization button (since it has no utility until the configuration is done).

![configuration-never-synced](https://cloud.githubusercontent.com/assets/101482/23720993/997a0c3c-03fd-11e7-9b4a-8332b6dcc734.png)


### After successful configuration and synchronization
I assume that when the form is saved with a valid configuration values, synchronization will immediately begin. We could display a flash message after the Zotero ID and group/user type selections have been confirmed as valid to let the user know what's going on:

![flash-sync-started-message-only](https://cloud.githubusercontent.com/assets/101482/23720207/4dd10bac-03fb-11e7-8cc7-298338cc57b9.png)

For this feature, I think that the flash message is probably sufficient for providing status (versus a more elaborate status display to provide counts of items synchronized, etc., such as we use for indexing item status) but that could be open for debate.

### Subsequent visits to the Services > Bibliography page

When the admin returns to the Services > Bibliography page after an initial, successful Zotero synchronization, we provide a different text message with the last sync date, and add a synchronize button with some associated text at the bottom of the form:

![configuration-sync-button-v2](https://cloud.githubusercontent.com/assets/101482/23720430/df624f0e-03fb-11e7-8c08-40344e020314.png)

(the sync button uses the `.btn-default .btn-sm` classes for styling)

When the admin clicks the Synchronize with Zotero button, assuming the configuration hasn't changed and there are no errors related to connecting with the service, we'd again show the flash message for status:

![flash-sync-started](https://cloud.githubusercontent.com/assets/101482/23720527/25a44f8a-03fc-11e7-89cc-84f7367f8269.png)

**Comment by drh-stanford** [comment]
@ggeisler @blalbrit we have a few questions about the UX...

1. What happens if the sync fails? The sync is happening in a background job and it's likely that the job will take ~10 mins or so.
1. The last screenshot should have a Zotero ID in it -- our understanding is that it the only way to get the Sync button to show (to have an ID and to have had a successful run).
1. It's a little confusing to have the Sync button and the Save Changes buttons so close. Can we somehow put some distance to the "status" information -- like a different section of the page, for example?
1. How does the user know when the sync is completed successfully? Is it just that status line text?
1. What does Save Changes do if the Zotero ID has changed? WIll it rebuild everything against a new Zotero library, right?

**Comment by ggeisler** [comment]
@drh-stanford (@blalbrit feel free to chime in if you disagree with any of my responses): I'll answer the easy ones first:

> The last screenshot should have a Zotero ID in it -- our understanding is that it the only way to get the Sync button to show (to have an ID and to have had a successful run).

If you mean the Zotero ID should be showing in the input field, yes, I agree. I thought of that after posting the comment, but had already deleted my session where I was doing the mockup. I meant to edit the comment to mention it but forgot.

> It's a little confusing to have the Sync button and the Save Changes buttons so close. Can we somehow put some distance to the "status" information -- like a different section of the page, for example?

I'm not sure I agree with the button placement being confusing. The Save changes button is in the same location on every page and the admin user is likely used to it being in that location. The synchronize button is a different color, aligned left versus the Save changes button being aligned right, and it's more directly associated with the form (that is, it's right after the text in the last form field) so unless we have some real evidence that users are likely to be confused I'm not sure this is a problem worth reorganizing the page for. But if you guys have another proposal in mind let me know.

> What does Save Changes do if the Zotero ID has changed? WIll it rebuild everything against a new Zotero library, right?

Yep, that's what I'd expect as a user. In that scenario it should be like the first time they entered an ID and synced. (So even if it fails, the previous references should be discarded, because the ID that was used to sync them was removed by the user.)

Items 1 and 4 deal with status and are more complicated. The mockup assumes a pretty simplistic approach to status notification. If we want to stick to simplistic I'd suggest that if the sync fails, we show a flash message notifying the user of the failure:

![curation_-_dashboard___ancient__medieval__and_early_modern_manuscripts_at_stanford_-_online_exhibits](https://cloud.githubusercontent.com/assets/101482/23879448/5e572dae-080a-11e7-8e7c-736a522b248e.png)

and add a line at the top of the synchronization status (before the "Exhibit items have never..." or "Exhibit items were last synchronized..." lines) that says:

> Zotero synchronization failed on 2017-03-13.

I'd only show the last failure date and of course omit the text when the sync next succeeds.

In this simplistic approach, my answer to question 4 would be yes, the status line text, and maybe a flash message like:

![curation_-_dashboard___ancient__medieval__and_early_modern_manuscripts_at_stanford_-_online_exhibits 2](https://cloud.githubusercontent.com/assets/101482/23879589/45813ecc-080b-11e7-9fe1-6738cc4407af.png)

We could also handle items 1 and 4 in a more informative but more involved way, such as doing something similar to the status progress we show for indexing items. I didn't suggest that previously because I know we spent quite a bit of time getting that implemented and assumed that might be overkill for this feature, which is likely to have relatively few consumers. However, @jkeck probably has a pretty good handle on the item indexing status approach at this point so if @blalbrit and the team think we can do something along those lines for status, let me know and I can come up with a mockup for displaying status that would be more informative than the more simplistic approach proposed above.

**Comment by jkeck** [comment]
I think the flash messages assume that either a page load has happened (e.g. redirect after form submit) or that the user hasn't navigated away from the page.

Perhaps we're overthinking this a bit too much, particularly as @ggeisler mentions, this is likely to have few consumers.  The strategy that we take for the indexing status display would add significant complication to completing this issue.

**Comment by blalbrit** [comment]
+1 @jkeck - I don't think we need a status report in this iteration of the bibliography tool

**Comment by mejackreed** [comment]
@ggeisler Is the intent here to view these as an unordered list in the UI `<ul>?

Or use separated `<div>`'s

**Comment by ggeisler** [comment]
@mejackreed I think unordered list items, unless you see a reason why using separate `divs` might be better/more flexible?

**Comment by mejackreed** [comment]
@ggeisler potentially if users wanted to copy and paste the bibliography, that may present problems? I don't know.. either way seems fine

**Comment by blalbrit** [comment]
@mejackreed @ggeisler - are we still talking about output from Zotero, specifically to support Parker bibliography - or has the conversation moved into a different area?

**Comment by ggeisler** [comment]
@mejackreed Yeah, maybe. I guess I just hesitate at `divs` because we might have to apply some additional styling to make a long list of items as easy to parse as what we get for free from a `ul` (e.g., indent after first line of each entry, add extra space between each one, or add a separator between them, etc.)

I don't think it matters too much and we could adjust if we get feedback. If @blalbrit has strong feelings we could go with he prefers.

**Comment by ggeisler** [comment]
@blalbrit Yes, we're talking about the bibliography output on the exhibit item detail page. The list of references and how they are presented.

**Comment by mejackreed** [comment]
Ah.. that makes sense @ggeisler . I'm 👍  for the list.. just wanted to discuss the different avenues.

**Comment by blalbrit** [comment]
my only requirement is that the bibliography be alpha-sorted and in a standard bibliography format (preferably Chicago).
