### ISSUE TITLE
Item records that are set to discoverable=none are displaying in exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#472]
Item record displays in list view with thumbnail -- in the Stanford Band exhibit -- when the item is set to dark in the SDR. When I click on the item, the item level MD displays, but there is no embed viewer on the page. The problem is, this item -- druid: xx235ny0602 (and a few hundred others in this exhibit) were set to dark (ie, access rights changed in the SDR) after the items were added to the exhibit. As a short-term, partial fix to at least remove the thumbnail displays in the exhibit, Ben has unshelved the content, which has killed the thumbnails. However, the records still display. This content is potentially embarrassing to the university and alumni, so the changed access rights setting really matters. The exhibit has been temporarily unpublished until this issue can be resolved. Sleuthing with Ben & Lynn has revealed, "anything with discoverable=none should **always** fail to index in Spotlight. The code seems to be ignoring that?" This is not an edge case, in fact, it is not uncommon for access rights to be changed in the SDR for content after it has been accessioned.

So:
1) Unless there is a misunderstanding about how sul-exhibits is working (ie, what the root cause is), anything with discoverable=none should **always** fail to index (task for this ticket), and

2) I am filing a separate ticket to request removal of the 491 druids from the Stanford Band exhibit that are now dark.

**Comment by caaster** [comment]
This issue should be investigated to make sure the behavior described is still occurring. If it is, this definitely needs to be fixed or it will trip us up again most likely.

**Comment by jcoyne** [comment]
I'm not sure that we have any attribute where we set "discoverable:none", so we may want to reconsider terminology we're using.  I think we mean "objects that have been set to dark".

I also wonder if this is a problem where we publish objects and they are successfully indexed and then we make them dark and republish them and they are not removed from the index.  Rather than dark objects getting indexed in the fist place. I know that the searchworks indexer has code to handle the deletes, I'm not sure that exhibits is listening to these publish events and knows that certain things should be removed.

**Comment by caaster** [comment]
Thank you for the corrective analysis @jcoyne & @corylown. Closing this ticket.
