### ISSUE TITLE
Provide fixture Bibliographic Object(s)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#573]
~~ Once the index has been altered to allow bibliographic items as first-class objects, the proof of concept will be to index fixture object(s) in order to proceed.

Requirements:
* fixture objects

Please feel free to expand this story with developer user needs. ~~

Provide fixture(s) of bibliographic citations

**Comment by mejackreed** [comment]
In working on #583, I created two custom Zotero translations that may be useful and fills some data gaps.

1. Adds tags to CSL JSON export

https://gist.github.com/mejackreed/49c0a41f2f03d850249132a0ed0c27ea

```json
{
   "id":"http://zotero.org/groups/1051392/items/ZDIFTVQJ",
   "type":"article-journal",
   "title":"Henry Lovelich’s Merlin",
   "container-title":"PMLA",
   "page":"473-84",
   "volume":"67",
   "shortTitle":"Ackerman 1952b",
   "author":[
      {
         "family":"Ackerman",
         "given":"R. W."
      }
   ],
   "issued":{
      "date-parts":[
         [
            "1952"
         ]
      ]
   },
   "keyword":[
      "xd494bt3141"
   ]
}
```

2. Uses URI as BibTex key instead of a random algorithm

https://gist.github.com/mejackreed/c0f08ebba4b4cf211f3c4f7abb785a44

```
@article{http://zotero.org/groups/1051392/items/ZDIFTVQJ,
	title = {Henry {Lovelich}’s {Merlin}},
	volume = {67},
	shorttitle = {Ackerman 1952b},
	journal = {PMLA},
	author = {Ackerman, R. W.},
	year = {1952},
	keywords = {xd494bt3141},
	pages = {473--84},
	annote = { KAW},
	annote = {The following values have no corresponding Zotero field:custom1: 8}
}
```

To use, you need to drop these into your `./zotero/translators` directory underneath the "Zotero Data Directory" https://www.zotero.org/support/zotero_data

**Comment by mejackreed** [comment]
I'm not sure yet. I think this is part of the process to get things setup.

**Comment by drh-stanford** [comment]
Ok, I've added the CSL JSON with tags format to the 4 fixture objects in https://github.com/sul-dlss/exhibits/pull/593.

**Comment by drh-stanford** [comment]
I've put the custom translators from the gists into our box folder here: https://drive.google.com/open?id=0B5fLh2mc4FCbV0ZnMElMejltN1U -- I used them to generate the fixtures in #593.
