### ISSUE TITLE
Design for search results with bibliographic items as first-class objects

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#575]
@ggeisler has started on this

**Comment by mejackreed** [comment]
Should the bibliographic metadata (author, date, etc. be searchable and facetable?)

**Comment by ggeisler** [comment]
Good question. I think we should get @blalbrit's thoughts on this. Our decision should be based on how we expect users to use the Parker site, and I'm not sure the extent to which they would want to search on bibliographic metadata versus just seeing it in the context of the work they do to find and use manuscript documents.

**Comment by blalbrit** [comment]
Hi @mejackreed and @ggeisler I do have some thoughts on this, based on how the bibliography has been used to-date in Parker 1.

Thought 1: Based on Google analytics, over the last three years, bibliography search, as it was constructed in Parker 1.x, has accounted for < 1% of Parker on the Web traffic. So my feeling is that we don't need to go too deep on facetable etc. based on known use over time (if we extend the analytics back to 2009 when the site launched, we're just over 1%).

Thought 2: The most common behavior within the bibliography search was to search on a specific manuscript in order to get the bibliographic citations associated with that manuscript. This feature is being supported by including the full citation list in the manuscript item show page.

Thought 3: The next most common behavior was to search on a specific short title or author name to find a specific full bibliographic citation.

Thought 4: My feeling is this, based on user evidence and known needs:
a) While user bibliographic search plays a minor role in the overall site analytics, it's extremely valuable to the librarians and to expert users
b) just listing the citations on each manuscript page covers a major portion of the user need
c) being able to search on an author name or publication title (or any text associated with a bibliographic citation? we should talk about how much is valuable for searching) and finding all manuscript records where that string appeared would fulfill another major portion of the user need
d) being able to click from a citation in a manuscript show page back to a Zotero record would fulfill all the rest of the known user requirements for the front end (not including the actual load/index requirements)
e) Anything beyond the above - all of which I think is covered in the current user stories and iterations on design work - is beyond the scope of MVP as currently conceived.

@mejackreed - do you have some thoughts about this based on making bibliographic items first-class objects? That is, are you seeing possibilities that you find interesting, or are you just asking what the requirements are? If the latter, I hope I've answered - if the former, let's chat more.

**Comment by mejackreed** [comment]
Thanks for the feedback @blalbrit . From an implementation standpoint:
 - We have the data already, and we can index it for display or search (or both!) quite easily now, we just need a direction
 - Based off of our discussion at story time last week on filtering by "Manuscript" or "Reference" i'm more inclined to say we should index the basic metadata for both (search and display)
 - This path provides a bit of a different user experience than @blalbrit describes above but I think makes life easier (things are more consistent with how Spotlight works) and will be overall very useful. This will be a similar discovery experience to ArcLight

**Comment by blalbrit** [comment]
Okay @mejackreed - I'm interested, but you are expanding MVP scope. Let's discuss today - I don't consider this a done decision until you, @caaster and I have agreed on approach.

**Comment by ggeisler** [comment]
Based on the comments above, it feels like the best balance of utility for the user and minimizing complexity in the UI would be to enable searching of bibliographic reference metadata fields (we already intend to show references as search result items) but not be facetable, if possible. That is, from @blalbrit's description of previous use, it doesn't seem that facets for reference fields would be used much (given the user will be able to search on a "short title or author name") and showing them as facets will just clutter the facet sidebar and present labelling challenges (e.g., distinguishing between manuscript "Date" and reference "Date").

Regarding @blalbrit's Thought 4, if it is important that the user can get to the actual Zotero record, on the Zotero site, then I propose we add a link to the reference show page. But still use the reference show page as the initial target for a click on a reference in a search result or from the bibliography list on a manuscript show page. That enables the user to see everything they would see on the Zotero site, but keeps them in the exhibit context. It also follows the general convention of clicking on a search result going to a show page, rather than an external website.

@blalbrit Does this sound okay to you? My impression is this approach would not add all that much more effort to implement and would provide a much better user experience. The mockup for the reference show page is in this ticket: https://github.com/sul-dlss/exhibits/issues/605. It's not clear to me from your comments on this ticket if you've seen that.

**Comment by blalbrit** [comment]
@ggeisler 👍 to all you've said above.

**Comment by ggeisler** [comment]
How the actual search results page might look might require further discussion, but here's a mockup to get the discussion started.

I'm assuming that the reference item fields will appear on the Configuration > Metadata page, so that the curator will pick the ones that are actually shown in the results (mockup represents my recommendations, but this is certainly open to debate and easy to adjust in the app). Since the reference and document (manuscript) fields will mostly mutually exclusive (and fields not relevant to one type or the other will be null and thus not presented in the UI), I think the differing fields shown in the mockup for the manuscript and reference result items is feasible?

We already have a generic default thumbnail image to be used for items without an image (in Spotlight) but ideally we could customize that to be more specific to the reference type item, as shown in the mockup.

![spotlight_graffle__parker__public___reference_results](https://user-images.githubusercontent.com/101482/31030936-f0a759ba-a50b-11e7-8599-0e1f45642968.png)

**Comment by mejackreed** [comment]
My intention wasn't to expand scope, but just to simplify. Making some fields faceable, some searchable, and some only displayable is totally possibly. The more differences the more complex it is, consistency is all I was aiming for. We can do whatever is needed here.
