### ISSUE TITLE
Implement bibliography upload tools in admin/curator dashboard

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#577]
This depends on implementation choices made to support upload choices. @ggeisler has already done design around this (not sure where those docs are, or if they are in a state of flux based on implementation decisions).

Requirements:
* Method of initiating a bibliographic data upload
* progress indicator (nice to have)

**Comment by drh-stanford** [comment]
I think this may be finished -- see #611

**Comment by mejackreed** [comment]
@blalbrit would you like to leave this open

**Comment by ggeisler** [comment]
More design to be done, just because the area where the initial implementation of this was done needs rethinking to deal with the several features like this one that have been sort of tacked on over time. I think it's worth reorganizing the various tabs and buttons so the various ways of adding items are more clear. Design to be done in #586.
