### ISSUE TITLE
How should the curator set the exhibit manifest pattern in admin UI?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#613]

**Comment by ggeisler** [comment]
@blalbrit Can you provide some example(s) in this ticket of how the curator will want to change the manifest pattern?

**Comment by mejackreed** [comment]
The default url pattern: `https://purl.stanford.edu/hp566jq8781/iiif/manifest`
What we would like it updated to: `https://dms-data.stanford.edu/data/manifests/Parker/hp566jq8781/manifest.json`

**Comment by mejackreed** [comment]
I was thinking something like: `https://dms-data.stanford.edu/data/manifests/Parker/#{:id}/manifest.json

**Comment by ggeisler** [comment]
Okay, great, thanks @mejackreed

**Comment by mejackreed** [comment]
@blalbrit Is it going to be problematic setting this for the entire exhibit? That seems like the best / ease of use thing to do for a curator.

**Comment by blalbrit** [comment]
For Parker - they all follow that pattern @mejackreed so I think this is ideal.

**Comment by ggeisler** [comment]
Here's a first pass at this. I'm not totally up on IIIF stuff so the wording might need to be updated to be more accurate/appropriate. Since this is a feature intended for SUL (I assume, but I can adjust if we think this should go in Spotlight instead of Exhibits) I've changed the URL examples a bit to use `druid` rather than `id`, since I believe an exhibit admin that needs to configure this feature should be familiar with what a DRUID is.

(If we go with this, I have another mockup that shows how the existing Viewer page will need to be adjusted to accommodate this new tabbed page.)

<img width="1227" alt="spotlight_graffle__parker__config___viewers" src="https://user-images.githubusercontent.com/101482/31154746-1412f45e-a85e-11e7-8fb4-f9247c9fb641.png">

**Comment by jkeck** [comment]
I do think that this (and the viewer switching) would ultimately be features that Spotlight could use (and has been mentioned by people in the community).  I think it would be great if we could pull this customization out and push it upstream.  There are some complicating factors around ensuring javascript libraries are loaded (and the correct versions) at the correct time, so I think we should get PO input before going that route (and we can def. begin by doing this locally).

**Comment by mejackreed** [comment]
+1 @jkeck and great design @ggeisler. One concern I have about the upstream mirador is adding that dependency onto Spotlight. Perhaps there is a way to make this more open so that isn't required?

**Comment by mejackreed** [comment]
@ggeisler would it be possible to move away from "druid" and to "id" somehow? The reason I mention this is this pattern could be used for non-druid based objects.

**Comment by ggeisler** [comment]
Okay, putting aside whether we want to do this in Spotlight (and what design changes that would require), here's an update that uses "id" instead of "druid". @mejackreed @jkeck Let me know if you think this needs further refinement. Also, @blalbrit if you have a chance to look at this that would be great.

<img width="1238" alt="pattern-tab" src="https://user-images.githubusercontent.com/101482/31186933-088441d8-a8e5-11e7-9709-f89d1f237324.png">

And here's how we'll need to change the existing viewer page. Basically we just need to add tabs and remove the existing "Item Detail Page" heading, which is now the name of one of the first tab.

<img width="1224" alt="viewer-tab" src="https://user-images.githubusercontent.com/101482/31186994-3d767fbe-a8e5-11e7-9b4f-0cb60113999d.png">

**Comment by ggeisler** [comment]
@mejackreed What do you think of this as the update for the lead-in text if we're not going to show the default pattern?

> If the location of IIIF manifests for items in this exhibit are to be retrieved using specific URL pattern, enter that pattern below, where the {id} token in the pattern represents the unique identifier of a given item. 

Also, if we don't have a default pattern, maybe we should rename the input label (can't remember if you're WIP already did this):

> IIIF manifest URL pattern

**Comment by blalbrit** [comment]
@ggeisler - this looks fantastic, thank you. thumbs-up all around.

**Comment by ggeisler** [comment]
Implementation underway in #612
