### ISSUE TITLE
Add document references to bibliography show page

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#650]
The bibliography show page needs to have a section of the documents/manuscripts that it was associated with (based on the identifiers supplied in the bibliographies keywords)

**Comment by aeschylus** [comment]
Based on some slack conversation we have the beginnings of two approaches based on the existing bibliography indexing strategy.

1.) Use the blacklight config to inject a partial in the appropriate place. I don't really understand how this works, but in theory is seems simpler. It might result in a slow page load due to blocking the request on a server-side API call.

2.) Reproduce what @drh-stanford has done in #660, and call out to the JSON API from the client page. This is pretty simple as well, and Darren has already given us a good example.

Long-term, it seems odd to call out to any API when the produced data is relatively static. Is there any way all these reference calculations can be done up front and stored until they need to be updated (once a year, say)?
