### ISSUE TITLE
Design for IIIF badges on show page and results page

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#679]

**Comment by ggeisler** [comment]
This is a feature that is trickier than it seems at first glance. I don't think we can simply add the IIIF icon alone and leave it at that, because relatively few users will know what IIIF is, and even fewer understand that they can drag the icon to a IIIF viewer. At the same time, we don't want to add a lot of text around the icon to explain what it's for, especially on the results page where it'll appear once for every search result. For example, I have a bunch of alternatives similar to this:

<img width="881" alt="spotlight_graffle__parker__public___search_results_with_iiif_badge 2" src="https://user-images.githubusercontent.com/101482/31300619-83b3523e-aaa9-11e7-9f84-4072538cf876.png">

where the "what's this" link expands to show more info:

----
<img width="558" alt="more-info" src="https://user-images.githubusercontent.com/101482/31300670-c2dda536-aaa9-11e7-82b0-66fb37f74bea.png">

----

but all the "what's this" links are going to be very repetitive on a results page.

Alternatively, how about we create a new icon that enables us to remove the text but still provides an indication that the IIIF icon has an action associated with it, like this:

<img width="1232" alt="results-icon-only" src="https://user-images.githubusercontent.com/101482/31300718-03d32142-aaaa-11e7-956b-9a3b4185c9ee.png">

This is a little less repetitive (without the text). But there's still the problem of some users not knowing what it does. So for users who do know, they can drag it to a IIIF viewer. For curious users who don't know, they'll likely click it. Unfortunately, clicking will go to the underlying linked resource, which is a IIIF manifest and not very informative for a naive user. But if we use Javascript to intercept the click event and rewrite the `href` value, we can make the link go to this page instead: https://library.stanford.edu/projects/international-image-interoperability-framework/viewers

That way the user can learn about what IIIF viewers are, etc.

If this approach seems feasible to others, we'll need to create a new icon and check with @snydman about the status of the lIIF viewers page we want to link to (the link to it is hidden in the sidebar of the [main IIIF page](http://library.stanford.edu/projects/international-image-interoperability-framework) on the Library site, so JV and I are not sure whether it is still a draft or needs updating, etc.).

If this approach seems good to others, the show page will use the same icon and click behavior:

<img width="1207" alt="show-page-icon-only" src="https://user-images.githubusercontent.com/101482/31300971-86e695ae-aaab-11e7-8cef-35584f5c4251.png">

**Comment by jkeck** [comment]
@ggeisler I like the 2nd version (w/ the arrow).  I wonder if we could also do something with hover text/or a tooltip, but that would obv. only have limited usefulness.

FWIW, I don't think we'll need to intercept the click event at all.  The drag-and-drop spec keys the manifest off of a `manifest` url parameter off the main link.  We can have the a link like `https://library.stanford.edu/projects/international-image-interoperability-framework/viewers?manifest=https://purl.stanford.edu/fw090jw3474/iiif/manifest` which if clicked on will go to the library.stanford.edu webpage but if drag-and-dropped into a viewer will use the value in the `manifest` parameter.

**Comment by ggeisler** [comment]
@jkeck Oh great! I didn't really think about how that href value worked but that's perfect without needing JS.

Yeah, we can certainly add some hover text but as you suggest I didn't want to rely solely on that.

Note that if it's not clear, the screenshot with the arrow is for the show page. The equivalent for the results page doesn't have an arrow but is the screenshot prior to that one.

**Comment by ggeisler** [comment]
Oh, maybe by arrow you mean the icon version with the arrow. If so, great, I think'll feel better on the page, especially for search results.
