### ISSUE TITLE
Index and make searchable text title

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#723]
See entry in https://purl.stanford.edu/cf386wt1778.mods `<tableOfContents>`

- [x] Index
- [x] Display
- [x] Searchable

**Comment by drh-stanford** [comment]
@blalbrit what should the label be for text titles? `Table of contents`?

**Comment by blalbrit** [comment]
@drh-stanford - yes, I think `Table of contents` - but again, would be helpful to have @ggeisler 's thoughts.

**Comment by ggeisler** [comment]
@blalbrit @drh-stanford Sure, given the element is `<tableOfContents>`, it also makes sense to me that the label be `Table of Contents`.

(Though -- and this might not be relevant to this ticket -- I don't completely understand how this element is used. In the example document given above, there is only one `<tableOfContents>` element. Is there only ever one such element per document? If there can be more than one, are they nested somehow?

It just seems a little unusual to refer to a single text string as a "table of contents" since in normal usage a table of contents is a list of entries, not a singular entry. But I could very well just not understand the relevant context here.)

**Comment by blalbrit** [comment]
@ggeisler @drh-stanford For modeling purposes, I used our simplest manuscript to build out the first table of contents. There can be hundreds of entries there depending on the manuscript. I think there are some questions about display of this element across the board in Stanford MODS display...

**Comment by arcadiafalcone** [comment]
tableOfContents is not a repeatable field in MODS, and does not have any child elements. This may be a case of doing internal `<br/>` tags for displaying each entry on its own line.

**Comment by ggeisler** [comment]
Okay, great, then it sounds like going with `Table of Contents` for the label is the right answer.

**Comment by camillevilla** [comment]
Indexing and basic display was added to the show page by #746. It will be separated by the usual commas and `and`. We might need some longer examples of `<tableOfContents>` down the line.

Test druid: cf386wt1778
![screen shot 2017-10-18 at 4 29 50 pm](https://user-images.githubusercontent.com/5402927/31747426-9f0c3344-b421-11e7-835d-017180806d85.png)
