### ISSUE TITLE
Review MODS model for Parker content

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#739]
See https://purl.stanford.edu/cf386wt1778.mods

This is the model we're looking at for MODS for Parker content (a few elements might shift - for instance, <abstract> might become <note type="summary">, but nothing major.

The complicating factors are the relatedItem contents with additional information.

Currently, much of that information gets lost (see https://purl.stanford.edu/cf386wt1778). We have additional tickets in the backlog to address some of this, but I wonder if @jkeck or others would be willing to look at where we're at now and flag potential concerns?

**Comment by jkeck** [comment]
It's worth keeping in mind the difference between how PURL/SearchWorks handles the display of MODS vs. how Exhibits handles the display of MODS.  (Apologies if this is already common knowledge)

Both SearchWorks & PURL provide the full content of the MODS XML to the [ModsDisplay](https://github.com/sul-dlss/mods_display) gem and configures that for display in the relevant application.  The `relatedItem` support in that gem has always been a bit lacking (primarily due to a lack of knowledge/decision around how the related item data should be represented in the rendered metadata). 

Exhibits, on the other hand, parses MODS metadata directly into fields in the solr index.  This is an important distinction because it is what allows the exhibit administrator to enable/disable, re-label, and re-order the exhibit fields for display in the various views of their exhibit.

Solving this issue for Exhibits won't solve the same issue in PURL/SearchWorks.  Ultimately, we can add more detailed related item support in the mods parsing stack used in Exhibits, but we'll also want to think about how these related items should be represented in the rendered metadata.
