### ISSUE TITLE
Design for fielded search of manuscript number, text title, incipit, etc.

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#743]
The Parker 1 site provides for fielded search. We need to design how the user will issue these searches in the Parker exhibit. My assumption is that we'd get the normal search results and that issuing the searches is the open question.

See #721, #722, #723, #724, #725 for context and which fields we need. Note that manuscript number should support exact matches.

cc: @ggeisler @blalbrit 

### Parker 1 interface for fielded search

![](https://user-images.githubusercontent.com/796990/31562978-41981d1c-b012-11e7-8d04-af507a65b667.png)

**Comment by ggeisler** [comment]
Below is an initial idea for meeting Parker's need for fielded search. Note that Language (#724) is not included in the mockup below because we're already showing language as a facet, so I'm assuming that is sufficient for the Parker user who needs to specify a language in a search.

Although this requirement has arisen in the context of Parker, my feeling is we should try to avoid any customized solution that doesn't have potential value for other exhibits. Exhibit-specific solutions start us down a road where we have to turn on/off features for different exhibits, which we might need to do at some point, but I think we should only go that direction if there's no other solution. So the proposal below is an attempt to stick to a generic, opt-in solution that Parker would just happen to take advantage of to meet its requirements (if I understand them correctly).

### Option 1 - Add Parker fields to field-based search list
If we exclude Language, there are four fields that need to be searchable individually (I am a little unsure about one of them, Manuscript title, because isn't that already the document Title field? Or maybe our addition of `Reference` and `Annotation` as document types changes that?). I don't see any problem from a UX point of view in adding these fields (or, in the future, new fields from other exhibits) to the list on the field-based search configuration page:

<img width="1250" alt="1-configuration-parker-fields" src="https://user-images.githubusercontent.com/101482/31732054-fc850e78-b3eb-11e7-9a7b-d69e4292c3c1.png">

Yes, it makes the field list longer, but this is a feature that the exhibit admin would only rarely have to use, and it's still much shorter than the Configuration > Metadata list, for example. 

The Parker fields should be unchecked by default, since they won't be relevant to most other exhibits. The Parker admin would then just need to uncheck any non-relevant fields (note 1 in the mockup above) and check the Parker-specific fields (note 2). So in the Parker exhibit, after configuration the fielded search menu would look like this to the user:

<img width="1217" alt="parker-fielded-search-menu-open" src="https://user-images.githubusercontent.com/101482/31732333-0c3e0c92-b3ed-11e7-9d13-9a01c397d31b.png">

### Option 2 - Enable search query refinement to specify term matching constraint
Ideally Option 1 above is sufficient for Parker's requirement. However, I think I saw elsewhere that exact term matching was also a requirement (and maybe a goal for other exhibits such as Lanciani). If we can't do anything with the way results are sorted (e.g., weight exact matches higher so they are first in the results list) to meet that requirement, then, in addition to Option 1, the approach in the mockups below might meet the requirement.

Add a configuration option that, when the search box is enabled, gives the exhibit admin the option of adding a Refine menu to the search box (note 2 in the mockup below). (If the search box option is unchecked, the refine menu option should be disabled, regardless of whether it is checked or unchecked.)

<img width="1092" alt="4-refine-menu-admin" src="https://user-images.githubusercontent.com/101482/31733675-3c66362a-b3f1-11e7-87f0-20f420854ff2.png">

When checked, a Refine menu is added to the search box:

<img width="1279" alt="2-refine-menu" src="https://user-images.githubusercontent.com/101482/31733702-5300e470-b3f1-11e7-9bab-4615916ffb6c.png">

When opened, the Refine menu looks like this:

<img width="1275" alt="3-refine-menu-open" src="https://user-images.githubusercontent.com/101482/31733729-69f4ffea-b3f1-11e7-8dcf-e06dfffb947c.png">

This would give the user the capability of specifying an exact match. For example, the Parker user would select "Manuscript number" from the field menu, enter a manuscript number, and select "Exact phrase" from the refine menu to get back just the manuscript with the specified number.

(Note that I'm not sure that the "Begins with" option is worth adding, but included it for discussion.)

I don't especially like this option myself, because the Refine menu adds to the visual clutter of the search box area and uses more space in the main menu bar row. But only exhibits that need the refine search options would have to display it, so hopefully most exhibits will leave it unchecked and it won't affect how they look.

**Comment by blalbrit** [comment]
@ggeisler - agree re: language not being included in fielded search.

**Comment by drh-stanford** [comment]
@ggeisler I think this looks great. A couple comments.

For Option 1, if I weren't a Parker admin, I'd find the labels confusing. If we're going to enable those fields for all exhibits (defaulting to Off), I think we need to clarify them. Or, should we show those fields *only* for the Parker exhibit?

For Option 2, I think that Solr provides support for those options (I'll need to dig into specifics if needed), but we'd likely be better off not surfacing them in this way and rather use our ranking algorithm, as you point out, to boost the exact matches further as needed for the Manuscript Number. We can do AND's and OR's using the Solr query language already -- and starts with would be: `search*`. 

@blalbrit It would be helpful to have use cases/examples for each type of query we want to support. For example, `elephant AND tiger` and `elephant tiger` yield no results, but `elephant OR tiger` does (this is current behavior).

**Comment by ggeisler** [comment]
@drh-stanford Thanks, response below:

> For Option 1, if I weren't a Parker admin, I'd find the labels confusing. If we're going to enable those fields for all exhibits (defaulting to Off), I think we need to clarify them. Or, should we show those fields only for the Parker exhibit?

I'm not sure we want to show the fields only for Parker, because then we get into having to have some conditional code that is dependent in some way on a particular exhibit. I don't think we've had to do that yet, and it seems better to continue to not have to do it if possible. Although if other options don't seem sufficient, that approach would seem pretty foolproof for preventing checking fields that don't apply to an exhibit.

As for the clarifying label approach, I understand your concern but am not sure it's actually a big enough potential problem that it requires us to figure out how to add clarifying information. I think of it this way: an admin of a non-Parker exhibit will come to this page, see a handful of field names that are unchecked and don't match field names for documents in his or her exhibit. It's certainly possible, but seems unlikely, that the exhibit admin will then purposefully check these fields that don't seem familiar for his or her exhibit documents. (Note the exhibit admin will already see many fields on the Configuration > Metadata page that aren't relevant to a given exhibit.)

On the other hand, I don't think we want a scenario where the admin does the wrong thing and checks fields that aren't present in the exhibit documents (because users will see fields they can search but aren't actually going to return anything). We could add some clarifying info as you suggest (added paragraph indicated by arrow below):

<img width="885" alt="field-list-text-update" src="https://user-images.githubusercontent.com/101482/31745356-3bec25d0-b417-11e7-923e-569223f179bc.png">

Although there's still no guarantee the admin won't ignore (or not read) that warning text. I don't suppose there is any way we could validate that each field checked on this admin page is a valid field for the exhibit documents? If we could ignore checked but invalid fields, or better yet, disable or hide invalid fields on the field list page (hiding based on the field not being present in the exhibit documents, not based on the specific exhibit), that would be even better.

> For Option 2, I think that Solr provides support for those options (I'll need to dig into specifics if needed), but we'd likely be better off not surfacing them in this way and rather use our ranking algorithm, as you point out, to boost the exact matches further as needed for the Manuscript Number. We can do AND's and OR's using the Solr query language already -- and starts with would be: search*.

I would love it if we don't have to add the Refine menu so it would be great if we can explore a ranking solution to the exact match requirement.

**Comment by camillevilla** [comment]
Here are notes from Story Time (10/19):
- Issue with fielded search — how to make fielded search configurable for Parker-specific fields but not introduce potential for non-Parker exhibits to mistaken select fields that don’t exist in their exhibit (could result in confused users and require service management involvement)?
  - Not practically feasible to detect which fields are used by a given exhibit (e.g. do all records use manuscript number?) and hide those that are not from the fielded search configuration
  - We do already have feature flagging in place that enables us to restrict a feature to a given exhibit, so we could use that to hide the Parker fields from other exhibits’ fielded search configuration.
  - One drawback of that approach is that if other exhibits in the future want to use the same fields in their fielded search, a developer or devops person would need to be involved to update the feature flag configuration. It would be preferable if this can be controlled by service management.
  - @blabrit says it is acceptable if only field can be searched at a time.
  - In terms of the requirement for exact matching on manuscript number field, we think we can boost the manuscript number field so that exact matches show at the top of the results, which would enable us to not have to implement the Refine menu in the mockup above.
- Analysis ticket: #777 feature flags + fielded search
- Down the road: superadmin UI for enabling / disabling exhibit-specific feature flags?
