### ISSUE TITLE
Enable "add from url" box in mirador manifest picker in exhibits pages.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#750]

**Comment by mejackreed** [comment]
Can we have some clarification from @blalbrit . Users are already able to add DnD manifests. Do they also need to add them from a text field?

**Comment by blalbrit** [comment]
Yes. Many IIIF implementers (BNF for instance) do not have dnd badges or (like Oxford) have flawed implementations.

**Comment by ggeisler** [comment]
@aeschylus or @blalbrit Can you be more specific about where you want to see this option? Which page(s) do you see this being added to?

**Comment by blalbrit** [comment]
@ggeisler - this is in the MIrador viewer itself as a config for the MIrador object load page. See:

![screenshot 2017-11-06 10 09 25](https://user-images.githubusercontent.com/796990/32456468-9cbeb7fc-c2da-11e7-84b8-151a044a54d3.png)

**Comment by ggeisler** [comment]
@blalbrit I'm confused. Do you mean you want to add something to the Mirador viewer when it is instantiated in an Exhibit show page? In other words, no exhibit page itself is implicated, just the viewer?

The ticket title says "... in exhibits pages" so that is where I'm getting confused. I don't know what "pages" we're talking about.

**Comment by blalbrit** [comment]
Sorry @ggeisler - I didn't mean to be confusing. This ticket is just about turning on a config in Mirador - there's no change to the exhibit page itself. I think @aeschylus wrote "in exhibit pages" because that was the place where the full Mirador viewer was likely to show up.

**Comment by ggeisler** [comment]
Okay, cool, thanks @blalbrit.
