### ISSUE TITLE
Allow facets on Browse category show page

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#772]
As a Parker on the Web viewer, I would like to be able to click on the "browse all manuscripts" button, and refine my navigation further by using facets.

As a Parker on the Web admin, I would like to be able to add facets to my "browse results" pages.

Currently, when clicking on a Browse category, we get a nice clean result view:
<img width="1430" alt="screenshot 2017-10-19 10 01 08" src="https://user-images.githubusercontent.com/796990/31783903-b525a118-b4b4-11e7-9244-34654326774e.png">

However, it is impossible to narrow result set down in useful ways. Would it be possible to allow an admin to configure the appearance of facets on a browse result page so that we could get something like the functionality available in current search results?

<img width="1509" alt="screenshot 2017-10-19 10 01 49" src="https://user-images.githubusercontent.com/796990/31783958-e7fe7cfe-b4b4-11e7-9bda-bb930d45e1a7.png">

**Comment by ggeisler** [comment]
Below are a few mockups to suggest how we might go about this. I do have some concerns about adding this feature, though.

One minor concern is that this feature was intended for the curator to consciously craft a useful way for exhibit visitors to look at one slice of the exhibit; if we add this feature I'm a little worried curators will be less likely to take the time to create multiple, useful categories and instead create fewer broad categories and assume the user can use the facets to find something meaningful. That starts to blur the lines with normal search query construction. But I do agree there could be valid use cases where a browse category could help the user hone in on an area and then they can use facets to dig deeper.

A bigger concern is whether we can manage the interaction with the facet sidebar to maintain the integrity of the browse category (i.e., keep it clearly different from an ordinary search results page). There are some minor things I noted in the mockups where I think we can manage that okay. But what I'm not sure about is what happens when the user clears any facet value that was used to define the underlying search result of the category itself. For example, if a user clears "Manuscript" from the current Parker "The Manuscripts" browse category, the result set is now the entire set of exhibit items, in which case it doesn't make sense to keep the user in the browse category context. So we might need to do some non-standard things with the facet sidebar to enable the user to filter with facets while maintaining the integrity of the browse category. 

### Curation > Browse Category page

The exhibit curator would have a new checkbox to enable or disable the facet sidebar for a given browse category. Pretty sure we want the default to be unchecked.

---
<img width="1022" alt="browse-category-configuration" src="https://user-images.githubusercontent.com/101482/31844477-c6b07ee0-b5ad-11e7-879f-3d6883d17122.png">

### Browse category page with facet sidebar enabled

This is an example page before the user has made any modifications using the facet sidebar. The facet sidebar reflects the search query that underlies the browse category (just "Manuscript" in this case).

---
<img width="1150" alt="browse-page-with-sidebar" src="https://user-images.githubusercontent.com/101482/31844500-e6cea0da-b5ad-11e7-994b-b1f70bc766dc.png">

### Browse category page with facet sidebar enabled

This is the example page after the user has chosen an additional facet value ("Christ Church, Canterbury") in the sidebar. Going back to my concern described earlier, if the user next decides to clear the "Christ Church, Canterbury" facet value, that's fine, it doesn't affect the underlying search result of the browse category. On the other hand, if the user clears the "Manuscript" facet value, I don't think the category context is valid any longer. But I'm not sure we can expect the user to understand the difference in those two actions.

I'm not arguing against this feature, necessarily, just pointing out that we might have to do some technical things (e.g., disable any facet values that are part of the underlying query, or not display the facet categories used for the underlying query at all) to ensure we don't create confusion for the user. I'd like to get reactions to what's here so far before exploring those options.

---
<img width="1130" alt="browse-page-with-sidebar-modified" src="https://user-images.githubusercontent.com/101482/31844620-b2108c40-b5ae-11e7-8563-2f69d43e9836.png">

**Comment by caaster** [comment]
Morphed to #816
