### ISSUE TITLE
Is it possible to manage the bibliography view in some way that allows expansion instead of endless scroll?

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#775]
From user feedback:

Looking at some of our ‘slimer’ mss it looks great, however once you get into the territory of 286 it does appear like a never ending list -- would it be possible to add some sort of scroll bar thing to make it less intimidating? Or perhaps collapsable? -- realising that I have no idea how difficult any of this would be to implement….

@ggeisler - thoughts?

**Comment by blalbrit** [comment]
(we may run into this with tables of contents as well)

**Comment by ggeisler** [comment]
@blalbrit I think you're correct that we'll need to think about this with the tables of contents, but let's address that in a separate ticket because I think the way we address each of these might be different (since the table of contents will be in the metadata list rather than a dedicated section at the end of the page).

For the bibliography, on the one hand I'm not sure this will be a problem for actual users because  the Bibliography section is the last section of the page. If an item has a long bibliography and the user is not interested in the bibliography, they wouldn't be scrolling the page down to see it all, would they?

On the other hand, the feedback refers to making it "less intimidating" so maybe the concern is just that an item page with a long bibliography will look too busy, or something like that. I could see an unstated concern that if a user hasn't learned that the bibliography is the last section of the page, that user could have to scroll through a long bibliography to see that there is in fact nothing else on the page to look at.

If we decide this is worth addressing (I'm on the fence), here are a couple of options that come to mind.

### Option 1 - Show/Hide the entire bibliography section

We could add a set of "show | hide" links next to the Bibliography title (note 1 in the mockup below) that just turn on and off the list of references. I think we'd probably start with the items shown, so the option is there to hide them from the initial display:

---
<img width="1215" alt="show-hide-control-hide" src="https://user-images.githubusercontent.com/101482/31796475-905e3492-b4de-11e7-90aa-9c71a92270ba.png">


When hidden, the page looks like this:

---
<img width="1217" alt="show-hide-control-show" src="https://user-images.githubusercontent.com/101482/31796490-9a4f76aa-b4de-11e7-901e-4bdfca61d80a.png">

This approach has a couple of drawbacks, though. First, by initially showing the complete list, it might not address the feedback that an item page with a long bibliography looks intimidating (it does give the user the control to make it look less intimidating, and more easily see there is nothing else below the bibliography). Second, I think it looks a bit odd to have a section heading with nothing under it, as in the "hidden" state (note 2 in the mockup above).


### Option 2 - Expand/Collapse buttons

I think this might be a better option.

We always show the first _n_ references (five, for example). If the item has more references than that, we show an expand button (note 3 in the mockup below):

---
<img width="618" alt="expand-button" src="https://user-images.githubusercontent.com/101482/31796300-cd663c00-b4dd-11e7-8fe8-ed74a3912780.png">

When selected that button will 1) expand to show the complete list and 2) will show a button at the bottom of the list that will collapse the list back to its initial state (assume the list in the mockup below has many more items than shown):

---
<img width="627" alt="collapse-button" src="https://user-images.githubusercontent.com/101482/31796332-ed4ca91e-b4dd-11e7-87f7-3b796d99550d.png">

**Comment by blalbrit** [comment]
Thanks for this @ggeisler - let's keep this in the backlog for now. I'm on the fence about it as well.

 I'll also file a placeholder ticket for the table of contents issue.

**Comment by ggeisler** [comment]
The Bibliography collapse/expansion goal is now represented as ready for development in #855 so I'm considering the design for it done.
