### ISSUE TITLE
Design & implementation considerations for long tables of contents

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#784]
This is a placeholder ticket for an issue that will likely arise with long tables of contents. Questions about the best way to display include expand/collapse; separate line per item; etc. More importantly, we'll be using the MODS relatedItem to manage additional information about the items in the table of contents. I'll pin some fixture data here with longer content lists.

cc. @camillevilla @ggeisler

**Comment by blalbrit** [comment]
Upon further investigation, tables of contents will likely not be an issue - MODS treats them as a single string with separators (-- or - in the examples I've seen). So it will really be relatedItem that will be under consideration.

**Comment by blalbrit** [comment]
Tables of contents have been updated for all Parker objects. A rather common mid-length example is: https://purl.stanford.edu/tx112pf2826 .

**Comment by camillevilla** [comment]
@ggeisler here's an experiment with a collapsed table of contents ([tx112pf2826](https://purl.stanford.edu/tx112pf2826)) for your consideration. As you can see...these table of contents really do stretch on 😥
![table-of-contents](https://user-images.githubusercontent.com/5402927/32354491-246fa766-bfe7-11e7-9025-10e269b1db2f.gif)

**Comment by blalbrit** [comment]
See also https://exhibits.stanford.edu/parker-2/catalog/sg197kx6643 for an extreme example.

**Comment by ggeisler** [comment]
@camillevilla Yeah, I think this is a good way to handle the TOC. I have some styling suggestions you might try out.

If we go with a button for expand/collapse, I'd suggest a couple of updates:

- Try a smaller button size (it looks like it might be the default button size; I'd try adding the `btn-xs` class to it
- Lighten the color by adding the `btn-default` class. Right now it seems like it's using `btn-primary` but we really only want to use that for buttons that we think the user is very likely to want to use on the page, such as Save or Edit or the main task the page is designed for. Here the expand button is more of a secondary action.

The general goal of those suggestions is to make the button blend in more with the page; I think a user interested in seeing the TOC will scan the metadata fields and see the button even if it is more subtle. There's nothing special about the TOC field that makes us need to draw attention to it above the other fields.

In fact, I wonder if we want to make it even more subtle and just use link styling (`btn-link`) rather than button styling? So instead of a button just a link that initially says "Open" and when expanded, changes to "Close"? That way it won't require any extra height and the vertical rhythm of the metadata fields isn't affected at all by the expand link.

**Comment by camillevilla** [comment]
Here's a couple new ones based off your suggestions, @ggeisler. 

## link styling
### open
<img width="476" alt="link open" src="https://user-images.githubusercontent.com/5402927/32393858-679412fa-c098-11e7-9be1-81501418f76c.png">

### close
<img width="544" alt="link close" src="https://user-images.githubusercontent.com/5402927/32393857-677edb7e-c098-11e7-967a-3225e4408b19.png">

## btn-default
### open
<img width="467" alt="btn-default open" src="https://user-images.githubusercontent.com/5402927/32393860-67bfb63a-c098-11e7-87f6-c53aa0dfbe6f.png">

### close
<img width="538" alt="btn-default close" src="https://user-images.githubusercontent.com/5402927/32393859-67a7acd4-c098-11e7-9d2c-502bb7f7ea03.png">

**Comment by ggeisler** [comment]
Personally I think the link styling is sufficient and less obtrusive. If you're willing to go with that, I'd suggest these updates to it:

- Change the labels (I know I suggested the ones you used, but seeing the implementation makes me think open/close doesn't work as well) to Show/Hide
- For the closed state ("Show" label), the icon show point to the right

> Show >
