### ISSUE TITLE
A-Z sort in collections facet not working correctly

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#810]
In the following exhibit:
https://exhibits.stanford.edu/data

The A-Z sort is not working properly in the collection facet:
https://exhibits.stanford.edu/data/catalog?q=&search_field=searchUUIDa791febd-f7aa-43e1-97ab-26519cec01d3

**Comment by ggeisler** [comment]
Another example, just to be clear it's not likely related to the exhibit itself (screenshot is after selecting the A-Z sort option):

<img width="585" alt="-_the_bob_fitch_photography_archive_-_spotlight_at_stanford_search_results" src="https://user-images.githubusercontent.com/101482/32285416-67df5fec-bee7-11e7-8ac5-6de5743a0fef.png">

**Comment by cbeer** [comment]
Ah -- collection is actually a compound field that includes a druid prefix. We'll have to consider alternative ways of indexing to support this use case.

**Comment by jkeck** [comment]
Re-opening this.  After a few convos, there is some concern about breaking browse categories that have been created from this field already.

Another approach proposed by @cbeer is to index the collection title into a new field to be used.  I _think_ that we would still want to keep the old field/data around to support existing browse categories, but this facet would not need to be shows to users/admins, would just need to be queryable by solr.  @cbeer please feel free to fill-in any additional details that might be pertinent.

**Comment by caaster** [comment]
Refer to exhibits #1037 - issue sub-task.

**Comment by jkeck** [comment]
In case it's helpful to wrap-up a little analysis here....

We have 727,309 documents that have the old `collection_with_title` field ([solr query](http://example.com/solr/select?facet=false&fl=id,collection_with_title,collection_titles_ssim&fq=collection_with_title:[*%20TO%20*]))
We have 715,686 document that have the new `collection_titles_ssim` field ([solr query](http://example.com/solr/select?facet=false&fl=id,collection_with_title,collection_titles_ssim&fq=collection_titles_ssim:[*%20TO%20*]))

This leaves a difference of 11,623 documents that need to be re-indexed so they have the `collection_titles_ssim` field ([solr query](http://example.com/solr/select?facet=false&fl=id,collection_with_title,collection_titles_ssim&fq=collection_with_title:[*%20TO%20*]&fq=-collection_titles_ssim:[*%20TO%20*]) / [csv of IDs](http://example.com/solr/select?wt=csv&rows=12000facet=false&fl=id&fq=collection_with_title:[*%20TO%20*]&fq=-collection_titles_ssim:[*%20TO%20*])).

It _might_ be possible that once we re-index all 11,623 documents that we could configure the existing `collection_with_title` facet field to use the `collection_titles_ssim` as the field name (and retain `collection_with_title` as the key)  so that existing facet configurations/saved searches/etc would continue to work (but will need to validate that).

**Comment by caaster** [comment]
@jkeck the csv of IDs link doesn't seem to go to the csv file....

**Comment by jkeck** [comment]
I've obfuscated our solr host URL in all of the links, but if you replace that with our real production server you can get the CSV.  Happy to ping you that privately on slack if you would like.

**Comment by caaster** [comment]
If we agree that reindexing the affected exhibits is a good course of action, I can reach out to creators to obtain permission to do so, although this will take some time/coordination. So let's discuss this and decide if we have the information we need to be able to make the decision. With help from Jessie, here is the list.

![image](https://user-images.githubusercontent.com/3210225/110993542-471fd400-832c-11eb-9f1f-61f33d22d89e.png)

**Comment by anarchivist** [comment]
This is just reported again (4/15/2022), specifically for the `data` exhibit:

<img width="835" alt="Screen Shot 2022-04-15 at 9 12 01 AM" src="https://user-images.githubusercontent.com/73732/163595220-4dc1685f-0f98-4742-9f6e-239956f09d20.png">

**Comment by corylown** [comment]
- [ ] Need a new list of impacted collections. (Do this now.)
- [ ] Cathy would need time to reach out to exhibit creators to get permission to re-index.
- [ ] Then we could re-index the collections
- [ ] Once the collection are re-indexed we can switch the app configuration to use the new field.

**Comment by corylown** [comment]
@caaster here's a current report of exhibits that would need to be re-indexed in order for us to fix the A-Z sort of the Collection facet:

**Public exhibits:**
```
data
exemplars
harrison
stanford-senate
oral-history
preventing-genocide
women-art-revolution
stanford-band
su-photos
hanna-house-collection
menuez
gatt
ua-maps-drawings
women
kzsu
community
tel-aviv
news-service
time-travel-japan
views-portraying-place-space
stanford-stories
lanciani
maps-of-africa
stanford-pubs
stanfords
ruderman
renaissance-exploration
mss
rare-music
chinese-ngos
heckrotte
activism
queer
cs
feigenbaum
ai
```

**Exhibits that require auth:**
```
h2-test
digital-bookplates
memorialchurch
gordon-maps
```

**deleted? exhibits (can ignore, but including for completeness)**
```
alcoa
bach-test
my-favorite-cats
kolb
```

**Comment by caaster** [comment]
Thank you @corylown. I will craft an email to send to all exhibit creators, send it, and nudge everyone until they all reply. Stay tuned! This will take time, and as I said good to get started now.

**Comment by corylown** [comment]
This A-Z sort issue should now be resolved for most exhibits. There are three exhibits that still use the old collection name field because they cannot be reindexed:

views-portraying-place-space
chinese-ngos
gordon-maps

The old collection name field now shows up as `Collection (deprecated)`. Old browse categories built using the old field should still work.
