### ISSUE TITLE
Add items button crashes browser for both Stanford Band & Stanford Photos exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#811]
Summary from Gary:

I cannot reproduce the problem on other exhibits. This makes me wonder if the problem is related to the large number of items in the exhibit. I think we'll need to ask a developer who understands more about what steps the Add items button triggers to see if it's related to the number of exhibit items or something else. 

Initial troubleshooting: The Copyright Renewals exhibit also has a large number of objects (246,448) but clicking Add items there does not show the same problem; the Add items form loads very quickly.

However, the Copyright Renewals exhibit is, I believe, kind of a special case. There are no collection objects shown and I think the items might have been added in a manual process. So it might not be a good comparison, or is a helpful example in that the difference in how items were added to the exhibit is a clue to the problem. 

I think the Stanford Band exhibit would be another good one to compare, since it has 112,374 items, but it too fails after clicking Add Items. So Band and Photos exhibits both fail on clicking Add Items, and both have large number of items in the exhibit.

**Comment by jkeck** [comment]
Initial benchmarking indicates that the issue is slowness caused by deserializing the index status of the documents associated with an exhibit (in the case of Stanford Band 132,775).  In order to drive the Item Status display that shows the individual status of of each item indexed, which is labeled as "Object Druids" (see [screenshot](#exhibits-object-druids) below), all 132,775 sidecars have to be looped through and have their index status deserialized for rendering in this partial.  I believe this deserialization of the item_status is where we're getting bogged down and the rendering of this partial is taking > 60s (and therefor throws a timeout error).  A similar benchmark just getting a column like ID was orders of magnitude faster.

I worry about this "Index Status" UI not scaling to the large numbers of documents we know that we'll need to handle (e.g. I'm not sure a scrolling list of > 100,000 rows in a table is useful at scale).

<img width="866" name="exhibits-object-druids" alt="obj-druids" src="https://user-images.githubusercontent.com/96776/32303868-9e480584-bf28-11e7-9b19-8f25057a5ffd.png">


```ruby
e = Spotlight::Exhibit.find('stanford-band')

Benchmark.bm do |x|
  x.report('Sidecars: ') { e.resources.first.solr_document_sidecars.map {|sc| sc.index_status[:ok] } }
end
```
```bash
user     system      total        real
Sidecars:  66.840000   3.950000  70.790000 ( 75.029967)
```

Not sure there is anything on the application side we can do as an immediate fix (e.g. making a more efficient query) that wouldn't require us significantly re-working how that panel is driven.

We could load it asynchronously (and let if fail when it takes longer than 60s) or we could limit the number of statuses we show (although this may lead to us not solving the problem we intend to with this status UI).  Ultimately I believe we need to re-think how we represent these statuses to users, particularly for exhibits with documents in the hundreds of thousands.

**Comment by jkeck** [comment]
After conversation w/ @ggeisler, I'm adding `design needed` to this ticket so we can use it for design discussion.

@ggeisler agrees that this isn't an optimal experience for long lists of druids.  Another possible approach discussed would be to show the total number of items and then provide an type-ahead input field that the user could type the druid to find the status (effectively mimicking what the user would most likely have to do which would be to use the browser's search function).

**Comment by ggeisler** [comment]
Here's a suggested design:

The only aspect of the Item Status panel we're changing is the nested Object DRUIDs panel. We'd update the intro text to this:

> There are 11,999 object DRUIDS indexed in this exhibit. To determine whether a particular item is indexed in this exhibit, or to check the indexing status of an item, begin typing the object DRUID below.

> Items displayed with the status of published were added to the exhibit. Items must be published (i.e., have a valid PURL) before they can be added to the exhibit.

where the "11,999" is dynamically populated with the actual object druid count.

And instead of the current table with list of druids, add a autocomplete search box.

<img width="500" alt="object-druid-search-1" src="https://user-images.githubusercontent.com/101482/32671520-ff6e6294-c604-11e7-8749-f1b4203888b6.png">

The idea being that as the user starts typing a druid, autocomplete would show matching druids to make finding a specific one quicker:

<img width="489" alt="object-druid-search-2" src="https://user-images.githubusercontent.com/101482/32671588-3b397e6c-c605-11e7-80c2-dc331ae42a82.png">


If the user clicks a druid from the suggest list, display a table to show the selected druid and its indexing status:

<img width="496" alt="object-druid-search-3" src="https://user-images.githubusercontent.com/101482/32671583-36ac6ba2-c605-11e7-8109-25564ffd31fd.png">

I think we can rely on the user seeing the suggest list empty as an indication that the entered druid is not in the exhibit, but we might consider showing a "No matches found." message instead of the table if the user hits enter when there are no matching suggestions? I'm not sure without seeing how it feels in action, so maybe we can figure that part out as the feature is implemented.

**Comment by jkeck** [comment]
This looks good to me @ggeisler.  One question I have is, should there be a threshold that we switch from a table view to a type-ahead lookup.  A scannable table may be a better UI for ~10 items but more than `N` would be better served by an autocomplete search.

**Comment by ggeisler** [comment]
@jkeck Definitely. If you can do that, I agree a static table for a reasonably small number of items is better than the lookup approach. 

Using `N = 10` seems like a fine cutoff. Thanks for suggesting this.
