### ISSUE TITLE
Truncate / collapse bibliography on a manuscript show page

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#855]
Per discussion and design from @ggeisler. Truncate collapse a long bibliography and only show the first 3 items

<img width="746" alt="screen shot 2017-11-08 at 6 08 11 pm" src="https://user-images.githubusercontent.com/1656824/32579634-d45290cc-c4af-11e7-949c-a544894d9aea.png">

<img width="1024" alt="screen shot 2017-11-08 at 6 08 43 pm" src="https://user-images.githubusercontent.com/1656824/32579645-e18bec5c-c4af-11e7-84ef-bb9e899a8fe0.png">

**Comment by jkeck** [comment]
@ggeisler by "long" do you mean anything more than 3 items or is there a larger than 3 threshold that we should still show all bibliographic entries for?

**Comment by ggeisler** [comment]
@jkeck Yeah, good question. It isn't too difficult to get fancy, how about we use 5 as a cut-off, such that:

- if the list has five items or fewer, show them all, with no expand/collapse button
- if the list has six items or more, truncate to three, and show the expand/collapse button

Otherwise, I'd just go with truncating any list that is longer than three items. So if it has four, we show three and the expand/collapse button. But if we can do the fancy option above, it feels like it would be a bit more elegant and eliminate the slightly odd cases of a list with 4 or 5 items being truncated and when expanded only showing one or two more.
