### ISSUE TITLE
Should `manuscript_titles_tesim` be generalized to a different name?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#872]
When looking into a ticket, I noticed this really isn't specific to manuscripts, but just where we store the data for parker. Should we generalize this to be more specific, or somehow limit this to Parker?

Solr query of all exhibits content now with this field:

https://solr-url/solr/exhibits_prod/select?fl=manuscript_titles_tesim,%20id&indent=on&q=manuscript_titles_tesim:*&wt=json

**Comment by camillevilla** [comment]
I'm thinking we should store this info in the pre-existing `title_variant_display` / Alternative title field. 

With the `mods_display` modal, we get desired behavior ("M.R. James Title" instead of "Alternative title") for free:

```
<titleInfo authority="Corpus Christi College">
  <title>
    Cambridge, Corpus Christi College, MS 069: Gregory the Great, Homiliae XL in euangelia
  </title>
</titleInfo>
<titleInfo displayLabel="M.R. James Title" type="alternative">
  <title>Gregorii Homiliae</title>
</titleInfo>
```
<img width="602" alt="screen shot 2017-11-15 at 12 00 51 pm" src="https://user-images.githubusercontent.com/5402927/32857523-f1e85a3e-c9fc-11e7-8ea5-0978bacd17b7.png">

**Comment by camillevilla** [comment]
This would affect our `Manuscript title` search field 🤔 
Possible options after indexing `manuscript_titles_tesim` to `title_variant_display`:

1. Rename `Manuscript title` search to `Alternative title` search. Remove feature flag and make this type of search available to other exhibits, but disabled by default. Retrain users to use `Alternative title`. 
2. Retain `Manuscript title` search (to match Parker 1), and keep it under a feature flag (#879).

**Comment by mejackreed** [comment]
Could the `Manuscript title` label just be changed manually by the Parker exhibit admin? Would that solve some of the problem 1 tickets?

**Comment by caaster** [comment]
For me to better understand the implications for Parker alongside exhibits-wide, I would benefit from an in-person chat looking at real data, or whiteboard.

**Comment by camillevilla** [comment]
@mejackreed yep, I think that'll do it. I didn't realize that was baked into the fielded search config UI. So option (1) would NOT require retraining users. 

![screen shot 2017-11-15 at 3 22 47 pm](https://user-images.githubusercontent.com/5402927/32865664-e942a3b4-ca18-11e7-8379-8cc906b80cf4.png)

@caaster more discussion tomorrow, but here's an overview of exhibits-wide implications:
- curators would be able to select `Alternate title` from the list of search fields 
- `Alternate title` would NOT be selected, by default
- `Alternate title` would search through MODS of the following type: `<titleInfo displayLabel="M.R. James Title" type="alternative">`

@blalbrit, here's more info on the proposed behavior for Parker:

## Before
### Current show page
![screen shot 2017-11-15 at 3 35 09 pm](https://user-images.githubusercontent.com/5402927/32866045-b1aca8f8-ca1a-11e7-8ff4-3b7c03228a9d.png)

## After
Note: the curator would be able to change the label from `Alternate title` to `Manuscript title`. 
### Show page
![screen shot 2017-11-15 at 3 38 47 pm](https://user-images.githubusercontent.com/5402927/32866160-19fdab96-ca1b-11e7-9012-5eac296c2e32.png)

### Modal
<img width="602" alt="screen shot 2017-11-15 at 12 00 51 pm" src="https://user-images.githubusercontent.com/5402927/32857523-f1e85a3e-c9fc-11e7-8ea5-0978bacd17b7.png">

**Comment by blalbrit** [comment]
@mejackreed and @camillevilla - please hold off on this until I get a chance to understand the change and its impacts. Without reflecting deeply, the manuscript title is drawn from two fields: title and alternate title. Searching for manuscript title != searching for alternate title. Are we agree about that?

**Comment by camillevilla** [comment]
@blalbrit 
I disagree. As it's currently implemented, Manuscript title only searches `manuscript_titles_tesim`, which only indexes `<titleInfo type="alternative">`. Alternate title and Manuscript title are drawing upon the same MODS value, so I'll be referring to them as equivalent below.

## Fixture
MS200 / bg021sq9590
**Title:** Cambridge, Corpus Christi College, MS 200: Baldwin of Ford OCist, De sacramento altaris.
**Alternate Title / Manuscript title:** Baldewinus de sacramento altaris

## Searches
- [Everything: Baldwin](https://exhibits-stage.stanford.edu/parker-00357808-6987-4f9e-9678-fbaad451fb91/catalog?utf8=%E2%9C%93&exhibit_id=parker-00357808-6987-4f9e-9678-fbaad451fb91&search_field=search&q=baldwin), returns both manuscripts and page details
- [Manuscript title: Baldwin](https://exhibits-stage.stanford.edu/parker-00357808-6987-4f9e-9678-fbaad451fb91/catalog?utf8=%E2%9C%93&exhibit_id=parker-00357808-6987-4f9e-9678-fbaad451fb91&search_field=manuscript_title&q=baldwin) returns no results. MS200 is excluded because its Title uses Baldwin, whereas its Alternate title / Manuscript title uses Baldewinus.
- [Title: Baldewinus](https://exhibits-stage.stanford.edu/parker-00357808-6987-4f9e-9678-fbaad451fb91/catalog?utf8=%E2%9C%93&exhibit_id=parker-00357808-6987-4f9e-9678-fbaad451fb91&search_field=search_title&q=baldewinus) returns MS200, because Title search uses both Title and Alternate title.

Also compare:
- [Title: sacramento](https://exhibits-stage.stanford.edu/parker-00357808-6987-4f9e-9678-fbaad451fb91/catalog?utf8=%E2%9C%93&exhibit_id=parker-00357808-6987-4f9e-9678-fbaad451fb91&search_field=search_title&q=sacramento) returns manuscript and page details
- [Manuscript title: sacramento](https://exhibits-stage.stanford.edu/parker-00357808-6987-4f9e-9678-fbaad451fb91/catalog?utf8=%E2%9C%93&exhibit_id=parker-00357808-6987-4f9e-9678-fbaad451fb91&search_field=manuscript_title&q=sacramento) returns only page details

**Comment by blalbrit** [comment]
Thank you for that clarification @camillevilla . So, from a user-perspective, "Manuscript Title" should include both the actual "manuscript title" (ie. the main title from the object MODS) and "Alternate Title(s)" (ie. the title/type="alternate" at the object level in the MODS).

As an example, MS 231 MODS has:

  <titleInfo authority="Corpus Christi College">
    <title>Cambridge, Corpus Christi College, MS 231: Terence, Comedies</title>
  </titleInfo>
  <titleInfo authority="James Catalog" type="alternative">
    <title>Terentius</title>
  </titleInfo>

Expectation: fielded search on MS title on: "terence", "comedies", or "terentius" would all return MS 231.

**Comment by mejackreed** [comment]
Per @camillevilla 's extensive work on this, I think we have a shared consensus on the feature. I'll try and summarize. We already support @blalbrit's fielded search criteria with the following searches:
 - https://exhibits.stanford.edu/parker-2/catalog?utf8=%E2%9C%93&exhibit_id=parker-2&search_field=search_title&q=terence
 - https://exhibits.stanford.edu/parker-2/catalog?utf8=%E2%9C%93&exhibit_id=parker-2&search_field=search_title&q=comedies
 - https://exhibits.stanford.edu/parker-2/catalog?utf8=%E2%9C%93&exhibit_id=parker-2&search_field=search_title&q=terentius

These all return the expected MS 231.

We are supporting the Parker requirements from the already existing Exhibits title fielded search support (title + alt titles). I think the final thing just to be made aware of here is @camillevilla 's recommendation expressed in https://github.com/sul-dlss/exhibits/issues/872#issuecomment-344776343 . This recommendation (which I fully support) shows the alternate titles in a consistent matter with the platform. It also allows the Parker exhibit curator to change the title of the field from "alternate title" to "manuscript title" if that is the preference. 

As I understand it, this accomplishes all of the Parker goals and allows for consistency.

**Comment by blalbrit** [comment]
Thanks @mejackreed for clarifying that the fielded search for "manuscript title" is non-functional in the expected way, but that the "title" fielded search supports the required functionality of searching across the manuscript titles supplied (both current and historical catalog titles).

That removes the requirement for a "manuscript title" fielded search separate from "title", and I have no problem with the term Alternate Title as a field name, as that would be expected from the metadata.

I'm confused as to how we equated Alternate Title with Manuscript Title in the first place, but it sounds like thanks to @camillevilla 's good work everything is now resolved.
