### ISSUE TITLE
Should we update the help text on the Add User admin screen

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#998]
We have seen a few SUNet aliases as well as non-stanford addresses added.  We may want to add some help text that lets the users know the constraints of the kinds of users they can add to an exhibit.

**Comment by ggeisler** [comment]
@jkeck This seems like a good idea. What do you think about showing this `help-block` text below the input when the Add a new user button is selected?

> Enter a valid SUNet email address. Do not enter an email alias or an email address that isn't in the stanford.edu domain. 

<img width="441" alt="configuration_-_site_configuration_-_users___the_edward_a__feigenbaum_papers_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/101482/33744888-cfdbe354-db70-11e7-9671-86df216b5c5b.png">

**Comment by anarchivist** [comment]
12/19/2017: We're aware of a special case where sponsored SUNet IDs without a Stanford email address may not behave correctly (they won't get an invitation, and they may not see their exhibit under "Your Exhibits" - they can go directly to the exhibit URL to edit). The plan is to have the service team handle these cases for now rather than implementing a deeper fix.
